### ISSUE TITLE
"Arquivos neste projeto" disponível para mim está com links quebrados

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#105]
O título aparece em https://www.umlivroaberto.com/BookCloud/Volume_1 e clicando em "view", me direciona por exemplo, para https://www.umlivroaberto.com/Volume_1/master/view/geometria.html
onde sempre recebo a mensagem
Not Found

The requested URL /Volume_1/master/view/geometria.html was not found on this server.
Apache/2.2.22 (Debian) Server at www.umlivroaberto.com Port 443

**Comment by gutosurrex** [comment]
Corrigido!
