### ISSUE TITLE
Mensagem de erro ao submeter new thread

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#107]
Segue o thread e a mensagem de erro.

> Caros, achei bem interessante o uso de semelhanças para justificar a distributividade da multiplicação por escalar em relação à adição de vetores que aparece neste artigo (páginas 2 e 3). Também é coerente com a nossa apresentação de coordenadas de vetores em relação a uma malha (base).
> 
> Link para o artigo:
> https://periodicos.ufsc.br/index.php/revemat/article/view/12993/12094
> 
> 
> O local do nosso texto onde isso é feito está aqui:
> https://www.umlivroaberto.com/BookCloud/Volume_1/master/view/geometria_cap1_op_vet.html#propriedades-da-operacao-de-multiplicacao-de-um-vetor-por-um-escalar

![screenshot from 2016-12-26 13-29-09](https://cloud.githubusercontent.com/assets/16407253/21483785/833d55ee-cb6f-11e6-8b28-401cd55842c7.png)

**Comment by simas0** [comment]
Apesar da mensagem de erro o thread foi criado. Acabei criando dois threads iguais e precisei mandar deletar umas 4 vezes para conseguir apagar o thread extra.

**Comment by simas0** [comment]
Como o thread pode ser criado não é mais crítico.

**Comment by simas0** [comment]
Continua acontecendo.

**Comment by gutosurrex** [comment]
Os emails sao enviados?
--

**Comment by simas0** [comment]
Acho que não.

Em 26 de dez de 2016 19:46, "gutosurrex" <notifications@github.com>
escreveu:

> Os emails sao enviados?
> --
> Sent from my Android device with K-9 Mail. Please excuse my brevity.
>
> On December 26, 2016 5:57:20 PM GMT-02:00, Fabio Simas <

**Comment by gutosurrex** [comment]
Era um bug mesmo... Está funcionando de novo.
