### ISSUE TITLE
Aquisição do livro "Digital Technologies in Designing Mathematics Education Tasks:  Potential and Pitfalls"

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#113]
@simas0, dá para incluir na lista de livros a serem comprados? Me parece ser uma referência obrigatória em termos de atividades digitais.

Digital Technologies in Designing Mathematics Education Tasks: Potential and Pitfalls
(Mathematics Education in the Digital Era) 1st ed. 2017 Edition
by Allen Leung (Editor), Anna Baccaglini-Frank (Editor) 
https://www.amazon.com/Digital-Technologies-Designing-Mathematics-Education/dp/3319434217/ref=sr_1_1?s=books&ie=UTF8&qid=1483035739&sr=1-1&keywords=digital+technologies+in+designing+mathematics+education+tasks

This book is about the role and potential of using digital technology in designing teaching and learning tasks in the mathematics classroom. Digital technology has opened up different new educational spaces for the mathematics classroom in the past few decades and, as technology is constantly evolving, novel ideas and approaches are brewing to enrich these spaces with diverse didactical flavors. A key issue is always how technology can, or cannot, play epistemic and pedagogic roles in the mathematics classroom. The main purpose of this book is to explore mathematics task design when digital technology is part of the teaching and learning environment. What features of the technology used can be capitalized upon to design tasks that transform learners’ experiential knowledge, gained from using the technology, into conceptual mathematical knowledge? When do digital environments actually bring an essential (educationally, speaking) new dimension to classroom activities? What are some pragmatic and semiotic values of the technology used? These are some of the concerns addressed in the book by expert scholars in this area of research in mathematics education. This volume is the first devoted entirely to issues on designing mathematical tasks in digital teaching and learning environments, outlining different current research scenarios. 

![51rxugpjmjl _sx313_bo1 204 203 200_](https://cloud.githubusercontent.com/assets/7694624/21550775/b1c84f92-cde3-11e6-8e6c-f046e173c1c4.jpg)

**Comment by simas0** [comment]
Sim! Vou enviar uma lista no início de janeiro. Se puderem postar suas listas é melhor para pedirmos todos juntos.
