### ISSUE TITLE
Thread com tag geometria só aparece no início do projeto

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#115]
Criei um novo thread com apenas o tag Geometria e ele só aparece na lista de ramos... É para ser assim mesmo?

**Comment by gutosurrex** [comment]
Acho que isso está fazendo pouco sentido agora, não?

**Comment by simas0** [comment]
Faz 8 meses que este thread foi aberto. Não lembro mais da história. Vou fechar é esperar para ver se o problema torna a aparecer.

_Enviado do meu Lenovo K33b36 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
