### ISSUE TITLE
Livro sobre funções

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#117]
@cambrainha e @GladsonAntunes (cc: @wmrezende e @simas0), coloquei na Wiki aquele livro que trata exclusivamente sobre o ensino de funções. Aqui está o link:

[Dubinsky and Harel - The Concept of Function - Aspects of Epistemology and Pedagogy. ](https://www.umlivroaberto.com/wiki/lib/exe/fetch.php?media=discus:dubinsky_and_harel_-_the_concept_of_function_-_aspects_of_epistemology_and_pedagogy.pdf)

**Comment by GladsonAntunes** [comment]
Muito obrigado Humberto!

Abraço!

2017-01-09 10:09 GMT-02:00 hjbortol <notifications@github.com>:
