### ISSUE TITLE
Quando no espaço do usuário não se pode criar novo thread

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#119]
Clicando em "new thread" na página abaixo
![screenshot from 2017-01-25 09-56-27](https://cloud.githubusercontent.com/assets/16407253/22290109/487fa0ea-e2e6-11e6-8d81-685a9073154d.png)

obtém-se a tela a seguir.

![screenshot from 2017-01-25 09-56-31](https://cloud.githubusercontent.com/assets/16407253/22290112/4a468088-e2e6-11e6-9266-cefc2319827b.png)

**Comment by gutosurrex** [comment]
Cara, eu consertei do jeito mais tosco possível: retirando a opção "new thread" do perfil do usuário.

O problema é que quando estamos no nosso perfil, não existe um projeto claro para o qual estamos escrevendo esse novo tópico (o projeto é obrigatório em cada thread). Uma alternativa seria colocar uma página intermediária onde a pessoa escolhe o projeto e depois mandamos ela pra escrever o tópico.

Podemos conversar depois sobre uma solução melhor. Principalmente pra tentar possibilitar uma conversa entre usuários.
