### ISSUE TITLE
Atividade "Enchendo o cone"

### ISSUE THREAD

**Issue by cydara** [livro-aberto/BookCloud#129]
- que pena que a fórmula V(h) seja dada "de graça/pronta" para o aluno... Que tal indicar uma dedução para ele? Por exemplo, que tal dar pronta a fórmula do volume de um cone genérico e solicitar que ele mostre que, neste caso particular, o volume pode ser aproximado pela fórmula 25h?
- Não sou defensora de perguntas na forma "A que altura corresponde um volume de 105105 litros?"  - quem disse que ele é atingido neste contexto?
- corrigir (duas vezes) para "à altura" a frase "São feitas duas observações do volume, uma correspondendo a altura h e outra a altura h+1,"

**Comment by GladsonAntunes** [comment]
- Vamos alterar
- vamos ajustar os valores.
- ok
