### ISSUE TITLE
Atividade "Obtendo Expressões"

### ISSUE THREAD

**Issue by cydara** [livro-aberto/BookCloud#130]
- Por coerência com frase anterior "Quando nos deparamos com uma função é fundamental identificarmos os conjuntos domínio e contradomínio, e a maneira como os elementos desses conjuntos estão relacionados. ", não estaria faltando alguma coisa no enunciado dos itens (a) e (b)? Principalmente porque a função g não tem para domínio todos os reais...
- corrigir "lingaugem matemática,"
- estou achando a pergunta "Quando podemos afirmar que duas expressões geram a mesma função?", neste momento, um tanto estranha: as funções f(x)=x(x-1)(x-2) e g(x)=x(x-1)(x-2)(x-3) coincidem na tabel que tem para primeira coluna 0,1 e 2. 
A quê a pergunta acima pretende levar? Está faltando no mínimo um bilhete ao professor...
Será mesmo que a atividade e a pergunta levam à definição que segue?

**Comment by GladsonAntunes** [comment]
- consertamos
- consertamos
- De fato, se o domínio for o conjunto `{0,1,2}` as duas expressões que você colocou geram a mesma função, uma vez que coincidem em TODOS os elementos do domínio. Nesse caso, acreditamos que a atividade conduz à definição.
