### ISSUE TITLE
Sobre 1.3 Exercícios ( Funções)

### ISSUE THREAD

**Issue by cydara** [livro-aberto/BookCloud#131]
- Qual o significado de * em "2.∗ Considere" ? Ele não foi especificado neste capítulo...
- Para mim é incompreensível a pergunta "O que obtemos a partir do número 13717?" !!!! (perdi alguma coisa, hehe ?)
- faltou "?" na pergunta 3

**Comment by GladsonAntunes** [comment]
-  Foi uma marca que colocamos apenas para lembrar que era um exercício mais difícil.
- O item a) está relacionado com o processo do enunciado. 
- O item 3) ainda vai ser melhor elaborado.  Deixamos lá apenas para lembrar depois.
