### ISSUE TITLE
Sobre Aprofundamento (Funções)

### ISSUE THREAD

**Issue by cydara** [livro-aberto/BookCloud#132]
- Acho que "associa o triângulo de área x" deve ser trocado para "associa UM triângulo de área x." (caso contrário o próprio enunciado já é ambíguo)
- Que tal incluir-se a "Ajude o estudante a completar a tabela." o item "discuta com seu colega sobre a possibilidade de a segunda coluna ser completadas de outra forma. O mesmo para a terceira coluna.

**Comment by GladsonAntunes** [comment]
- Não revisamos essa parte. Mas nesse caso a ideia é mesmo ter a ambiguidade.
-  Ok! Modificado.
