### ISSUE TITLE
Sobre 1.5 Gráficos (Funções)

### ISSUE THREAD

**Issue by cydara** [livro-aberto/BookCloud#133]
- Sugiro que a frase "Especialmente quando se quer analisar grande quantidade de dados, apresentá-los em uma imagem, um gráfico pode causar maior impacto àqueles que o leem." seja alterada para 
"Especialmente quando se quer analisar grande quantidade de dados, apresentá-los em uma imagem, POR EXEMPLO, UM GRÁFICO, UM  maior impacto PODE SER CAUSADO àqueles que o leem."
- Várias imagens seguem esta frase, mas cores iguais não dizem repeito a uma mesma informação... Não seria o caso de colocar-se legenda para cada uma das imagens?

Em 1.5.1:,
- Sugiro alterar-se "Perceber **as** vantagens da representação gráfica em detrimento da tabela." para "Perceber vantagens da representação gráfica em detrimento da tabela." (nem sempre a representação gráfica é a mais útil. Por exemplo, o valor preciso da função em um ponto pode ser difícil de ser lido em um gráfico. Do jeito que está posta a frase, parece que sempre a representação gráfica é mais vantajosa do que uma tabela).
- sugiro substituir "contudo é importante estar atento de que os segmentos" por "contudo é importante atentar para o fato de os segmentos...não serem dados..."
- avaliar se no lugar de "é um conjunto finito." não poderia ser (para professores e alunos do EM) "é um conjunto DISCRETO", que é o mais correto.
- sugiro que seja explicado o significado de "CEO de uma empresa"
- corrigir "apresentar o dados"
- a frase "Uma função, essencialmente, relaciona duas grandezas ou variáveis," está incompleta, pois na verdade deveria ser "Uma função, essencialmente, relaciona duas OU MAIS grandezas ou variáveis," Acho que ela deve ser alterada, por conta de impedir futuramente o entendimento de um aluno de funções de várias variáveis...
- Acho que a frase "Uma função, essencialmente, relaciona duas grandezas ou variáveis, de forma que, uma vez estabelecida a maneira de associá-las, obtemos pares (x,y)(x,y) em que x pertence ao domínio da função e y=f(x)y=f(x)" deveria ser substituída por "uma função também pode ser apresentada / representada na forma de pares ordenados"  e o restante do parágrafo deveria vir depois da retomada de produto cartesiano.
- substituir a frase "No caso de funções reais de variável real, isto é, cujos domínio e contradomínio são o conjunto dos números reais (ou algum subconjunto dele) não conseguiremos enumerar da mesma maneira." por "No caso de funções reais de variável real, isto é, cujos domínio e contradomínio são o conjunto dos números reais (ou algum subconjunto INFINITO dele) não conseguiremos enumerar da mesma maneira."
- sugiro substituir a frase  "Cada uma das retas é conhecida como um eixo do plano cartesiano." por "Cada uma das retas é graduada, sendo por isso chamada um eixo do plano cartesiano. Convenciona-se que, no eixo horizontal,..."
- corrigir " estão marcados as segundas"

**Comment by GladsonAntunes** [comment]
- Alterado.
- A imagem é apenas ilustrativa.
- Alterado.
- Alterado.
- Alteramos para discreto.
- Colocamos.
- OK
- Achamos melhor manter.
- Alteramos para "No caso de funções reais de variável real, isto é, cujos domínio e contradomínio são o conjunto dos números reais (ou subconjuntos dele) pode ocorrer que não seja possível enumerar da mesma maneira." Pois subconjunto infinito ainda pode ser enumerável.
- OK
- OK
