### ISSUE TITLE
Atividade "Do Mapa para o Gráfico"

### ISSUE THREAD

**Issue by cydara** [livro-aberto/BookCloud#135]
A frase "Estender a definição para o conjuntos dos números reais positivos, a partir de uma tabela." requer aprimoramento: estender a definição de quê?
Função é uma relação, não pode ser estendida para um conjunto; além disso, a função não é numérica, então não é natural para o aluno uma tal questão...

**Comment by cydara** [comment]
Alem disso, corrigir também "Caso, alguma estudante "

Não acho que esta atividade seja adequada para já se introduzir a questão "estendendo uma função". Eu criaria outra exclusivamente com este objetivo.

**Comment by GladsonAntunes** [comment]
- Modificado para "Estender o domínio da função para ....".
- Alteramos.
