### ISSUE TITLE
Atividade "Voltando ao Elevador"

### ISSUE THREAD

**Issue by cydara** [livro-aberto/BookCloud#136]
- corrigir a frase "É importante que seus estudantes tenham a ideia equivocada de que sempre devemos “ligar os pontos”."
- a frase "A cada tempo está associado um único andar " não é real: existe um instante em que se está precisamente entre dois andares, por exemplo
- Sugiro alterar a frase "Suponha que desejamos determinar o tempo associado a cada um dos andares," para "Suponha que desejamos determinar o INSTANTE associado À POSIÇÃO EM QUE O ELEVADOR ENCONTRA-SE EM cada um dos andares,"
- Discordo da frase "e portanto é uma tarefa simples encontrar os pontos procurados": não acho que seja simples para o aluno, a partir do gráfico: por que os demais pares terão que se alinhar com estes marcados? Na minha opinião, esta é uma pergunta que o aluno terá que responder se vai responder a partir do gráfico.
- Não está havendo uniformidade na notação de par ordenado em "(0,14)(0,14) da figura e após 0,5s ele chega no andar de número 13, ponto (0,5;13). " Se é para haver alguma conveção, ela não foi explicitada ao aluno.
- A frase "Como não existem andares fracionários, vamos convencionar que o elevador só chega em um determinado andar quando ele para naquele andar. " tem que ser antecipada (basta ver um comentário anterior meu)

**Comment by GladsonAntunes** [comment]
-  kkkkkk...Que coisa!
- Modificamos para "a cada tempo indicado na tabela está associado um único andar" .
- Modificado!
- Alteramos a frase e incluímos uma orientação para o professor.
- Alteramos seguindo uma sugestão do Humberto.
- Alteramos o início e mantivemos a frase na mesma posição, pois pensamos que ela faz mais sentido naquele momento, quando construímos o gráfico.
