### ISSUE TITLE
Aprofundamento (Funções)

### ISSUE THREAD

**Issue by cydara** [livro-aberto/BookCloud#138]
- será que não fica melhor, no lugar de "sistema de coordenadas cartesiano", escrever "sistema cartesiano de coordenadas" ou "sistema de coordenadas cartesianas"?
- Opa! Função de DUAS variáveis reais!!! Então um comentário anterior meu sobre "função relacionar (apenas) DUAS grandezas" procede...
- A pergunta "Caminhando ao longo da borda inferior, afastando-se da origem, o que se pode afirmar sobre a temperatura na placa?" com certeza gera confusão para o aluno, pois a definição de crescente/decrescente foi dada para funções de UMA variável real, e aqui está-se trabalhando com funções de DUAS variáveis reais (pelo menos a fórmula está explorando isso)...

**Comment by GladsonAntunes** [comment]
- Sistema de coordenadas cartesiano - Modificado!
- Aprofundamento ainda será revisado. Vamos discutir mais sobre esse tópico no Livro.
