### ISSUE TITLE
Trocar a propriedade do ramo Geometria

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#140]
Este ramo é de propriedade do @mpfaraujo, mas já deveria ser de @hjbortol .

**Comment by simas0** [comment]
Também deve criar um ramo permanente do ramo Geometria com o nome "ramo_mpfaraujo".

**Comment by gutosurrex** [comment]
Mudei a propriedade. Agora o Marcos Paulo tem que criar um ramo novo e pedir pra eu torná-lo permanente.

**Comment by simas0** [comment]
@mpfaraujo, crie o ramo de Geometria, por favor.
