### ISSUE TITLE
perfil completo na plataforma para colaborador

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#143]
Formação superior
Maior titulação.
Cidade.
É professor? Em que nível de escolaridade?
Sabe LaTeX?
Sabe HTML?
Sabe programar? 
Sabe Python?
Já participou da organização de evento acadêmico?
Sabe editar figuras?
Sabe editar vídeos?

Quantas horas gostaria de dedicar por semana ao projeto? 
Não sei.
 Até 2 horas, 
entre 2 e 5 horas, 
5 e 10 horas, 
adorei a ideia, mas não quero ser solicitado. 
Mais de 10 horas.

Como você quer colaborar?
Fazendo sugestões acadêmicas nos materiais produzidos, 
aplicando o material na minha sala de aula, 
implemento as sugestões de outros usuários ou da equipe na plataforma, 
diagramação do texto em LaTeX, 
mantendo o site, implementando modificações dá plataforma (programando), 
organizando oficinas de professores,
Fazendo figuras para o livro.
Produzindo ou editando vídeos.

**Comment by simas0** [comment]
Por favor, avise quando a ferramenta estiver disponível. Precisamos dela para dar continuidade à obtenção de colaboradores.

**Comment by gutosurrex** [comment]
Feito
