### ISSUE TITLE
Muitos cliques para criar um thread

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#146]
Deve haver uma lista de tags pré marcadas quando clicamos em newthread. Eu mesmo deixei de criar alguns porque desanimo de ficar selecionando arquivos, eixo, pessoas cada vez.

Nesta nova fase em que as equipes se reúnem menos a boa comunicação, mais do que nunca será fundamental.

**Comment by gutosurrex** [comment]
Primeiro passo para melhorar isso. Agora não temos aquela lista de coisas pra marcar e sim um sistema de tags.
