### ISSUE TITLE
Eu deveria poder avaliar as submissões de Geometria

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#147]
Se eu já tenho este poder, gostaria de saber como utilizá-lo.  Do contrário pode me colocar como proprietário deste ramo, por favor.

**Comment by simas0** [comment]
Volta o Marcos Paulo para coordenador de Geometria, por favor.

**Comment by gutosurrex** [comment]
Você já pode fazer isso. Troque view por review na barra de endereços:

```
/<project>/<branch>/requests
```

Já troquei Geometria para o MP.
