### ISSUE TITLE
Novo projeto Metodologia com erro ao entrar

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#156]
Apareceu um erro ao criar o projeto, mas foi criado. Agora tento entrar e tem um erro que não consigo contornar.

![screenshot from 2017-05-16 22-56-53](https://cloud.githubusercontent.com/assets/16407253/26135316/17f7e822-3a8b-11e7-8bbd-bb38255fd5bd.png)

**Comment by gutosurrex** [comment]
Pode criar agora...

Abraços,
Augusto




Quoting Fabio Simas <notifications@github.com>:
