### ISSUE TITLE
Barra verde na janela de edição deve desaparecer após 5 segundos

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#159]
Quando salvamos um arquivo aparece a mensagem: "File saved succesfully" e ela não desaparece mais...

**Comment by gutosurrex** [comment]
Feito!

**Comment by simas0** [comment]
Some de supetão. Um pouco de efeitos visuais não faz mal :-P
A barra verde em que está escrito: You have signed in successfully. Ainda permanece lá até que se salve.
