### ISSUE TITLE
Discussões (threads) seguidos

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#160]
Criei um ramo de funções para inserir os comentários após as atividades (basta criar labels antes no início da seção). 

A imagem abaixo indica um thread criado por criar um label para a seção Funções, um para a subseção Apresentação e outro para a subsubseção Pluviometria no Sistema da Cantareira. Uma solução imediata é retirar as duas primeiras, mas isso aponta para um problema que surgirá muito em breve com o qual teremos que lidar. Sugestões de solução?
@GladsonAntunes, @cambrainha 

![screenshot from 2017-06-21 11-24-42](https://user-images.githubusercontent.com/16407253/27389459-d0d69d66-5674-11e7-89a8-9ec0290b5ee2.png)

**Comment by simas0** [comment]
Uma solução possível é que o texto do thread contenha o título da seção, e.g., onde se lê "Discussions (0)" poderia estar "Comentários sobre a Atividade Pluviometria do Sistema Cantareira" ou "Comentários sobre a seção Apresentação", etc.

**Comment by simas0** [comment]
Outra alternativa é que as discussões fiquem posicionadas logo antes da próxima seção (de qualquer nível, seção, subseção, subsubseção, etc.).

**Comment by simas0** [comment]
Um problema relacionado é o de atividades serem seções e não ambientes. Vejam o exemplo abaixo em que a discussão sobre a atividade "Obtendo expressões" se posiciona após o texto que está localizado após a atividade. A atividade termina na tabela. Isso vai gerar confusões sobre o conteúdo das discussões ali constantes: se sobre o texto que segue a atividade ou sobre a atividade.

![screenshot from 2017-06-21 11-57-35](https://user-images.githubusercontent.com/16407253/27390888-d772dd2a-5678-11e7-93fb-e76023e2bfbe.png)

**Comment by gutosurrex** [comment]
Tá lindo

**Comment by simas0** [comment]
Melhorou muito!! Mas o que significa isso?! Ou bem alinha à esquerda ou bem é centralizado....

![bookcloud](https://user-images.githubusercontent.com/16407253/27500346-950c7000-583e-11e7-81a4-f599cfce1348.png)

**Comment by gutosurrex** [comment]
O alinhamento eh outro issue.
