### ISSUE TITLE
Discussions poderia permitir inserir imagens

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#163]
O sistema de "Discussions" poderia permitir inserir imagens

**Comment by simas0** [comment]
Oi Humberto, a inserção de imagens na plataforma ainda não está finalizado.
Você pode usar imagens nas discussões do mesmo modo que no texto. Veja, por
favor, o projeto sintaxe, na plataforma para instruções sobre a inserção de
figuras.
Abraço!

Em 4 de ago de 2017 09:32, "hjbortol" <notifications@github.com> escreveu:

**Comment by hjbortol** [comment]
Vi como fazer! Obrigado!

**Comment by hjbortol** [comment]
Caros, usar o sistema descrito no exemplo é tedioso: é preciso fazer upload da imagem para algum lugar e, então, colar o código para depois atualizar a URL neste cóido. O ideal seria ter como em alguns sistemas: você copia e cola diretamente.

**Comment by simas0** [comment]
Achei que já havia um chamado para este problema, como não achei criei um específico porque este não é um problema sobre o sistema de comentários, é geral da plataforma. @hjbortol, veja se o issue #167 contempla a sua requisição, por favor. Este issue aqui está resolvido, por isso será fechado.
