### ISSUE TITLE
New thread: exibir o que foi postado

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#164]
@gutosurrex e @simas0,

No sistema atual, após registrar uma thread, o sistema vai para uma página para se criar uma nova thread. Acho que ficaria melhor se voltasse para a trhead recém-criada para ver como ela ficou e fazer possíveis edições.

**Comment by simas0** [comment]
Aumentei a prioridade porque está causando dificuldade de leitura nas discussões que não seguem a sintaxe certa do sphinx.

**Comment by gutosurrex** [comment]
Feito
