### ISSUE TITLE
Inserção de figuras na plataforma

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#167]
Precisamos de um sistema que permita fazer upload de figuras diretamente na plataforma, sem a necessidade de um url. O ideal é que a figura possa ser arrastada para o ambiente de elaboração como funciona nos editores de texto tipo Word ou mesmo no Gmail, na DokuWiki isso funcionava de maneira aceitável.

@hjbortol

**Comment by simas0** [comment]
Já temos como fazer upload na plataforma, veja #258 

Mas ainda faltam as funcionalidades: 
1. a figura possa ser arrastada para o ambiente de elaboração como funciona nos editores de texto tipo Word ou mesmo no Gmail,
2. possibilidade de se subir diversas figuras de uma vez.

**Comment by gutosurrex** [comment]
Esses pedidos são outros issues

**Comment by simas0** [comment]
estes novos issues foram criados?

**Comment by gutosurrex** [comment]
Acho que não
