### ISSUE TITLE
Não consigo fazer tabelas nos threads

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#169]
Copio uma tabela exatamente como está no texto, e no thread não funciona. Retirei todo o preâmbulo da tabela e funcionou.

O mesmo acontece com referências.

**Comment by gutosurrex** [comment]
As tabelas do texto tem um monte de opções chiques, como alinhamento, bordas... como está explicado no sytaxe. Mas para os comentários é impossível colocar essas opções avançadas, portanto as tabelas tem que ficar mais simplificadas.

No futuro próximo eu quero fazer os comentários wysiwyg, o que eu espero que seja uma coisa desejável. Mas mais uma vez, wysiwyg não vai permitir tabelas muito avançadas.

**Comment by simas0** [comment]
Não acho que seja importante. Melhor é colocar uma barra de ferramentas nos
comentários como nos issues do GitHub.

Em 8 de ago de 2017 10:58, "gutosurrex" <notifications@github.com> escreveu:
