### ISSUE TITLE
Índice remissivo

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#175]
Desenvolver uma maneira de se destacar um índice remissivo. O Robert Breezer fez algo muito interessante sobre isso no XML. Podemos conversar a respeito depois.

**Comment by simas0** [comment]
Por exemplo, no parágrafo abaixo define-se relação. Eu gostaria que existisse uma sintaxe, como a sugerida no parágrafo abaixo, em que o elaborador pudesse determinar o que está sendo definido, onde começa e onde termina a definição. Então em algum lugar pediremos o glossário de termos definidos no capítulo e ele retornará algo como uma lista de palavras que são hiperlinks, ao clicar, surge um pop up bonitinho com o trecho limitado no parágrafo, isso no HTML. No PDF tem a indicação da página em que  encontra-se o conceito.

> Na definição acima dizemos que uma função é uma relação que tem propriedades especiais. Estamos considerando a noção intuitiva que o leitor tenha de relação. Para evitar dúvidas vale estabelecer que ':def_relação: uma relação entre os conjuntos X e Y é qualquer subconjunto do produto cartesiano XxY.' Assim, embora uma função nos dê a ideia de uma ação, em sua definição formal, ela se confunde com o seu gráfico.

O que acha @hjbortol ?

**Comment by gutosurrex** [comment]
Perguntei aqui:

https://stackoverflow.com/questions/45970082/how-to-create-an-automatic-list-of-words-in-sphinx

**Comment by gutosurrex** [comment]
Descobri como fazer. Podemos começar colocando esses tags explicados abaixo. Já vai funcionar de cara no `html`. Para o `pdf` vou ter que fazer mais umas pequenas mudanças.

Funciona assim:

```
.. index:: ! função

Função é uma relação com certas condições.

Bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla, bla.

.. index:: ! função

Função é útil na vida.

Podemos definir várias :index:`funções <função>` pra fazer a vida melhor. Mas as mais legais de todas são as :index:`funções bijetivas <pair: funções; bijetivas>`.
```

Observe que podemos colocar a referência antes de um parágrafo, como em `.. index:: ! função`. Nesse caso a exclamação indica que essa é a referência mais importante do termo citado (terá um certo destaque no índice remissivo).

Mas podemos colocar índices no meio do texo também com ``:index:`isso <coisa>` ``. Onde `isso` é o que aparece no texto e `coisa` é o que vai pro índice remissivo.

Existem termos com duas palavras também, como  ``:index:`funções bijetivas <pair: funções; bijetivas>` ``. Esse aparece na letra `f`e na letra `b`.

Para ver o índice, aperte o nome do ramo no menu acima e clique em glossário.

**Comment by gutosurrex** [comment]
Eu sugiro pararem de usar `.. glossary::` que eu vi em alguns lugares do texto. Esse outro método é muito melhor.

**Comment by hjbortol** [comment]
Excelente!

Uma dúvida: como funciona a questão de variações da palavra-chave. Por exemplo, em LaTeX, podemos fazer:

\index{função}
\index{função!par}
\index{função!injetiva}
\index{função!constante}

que no índice irá aparecer

Função 9
   constante 11
   injetiva 15
   par 10

**Comment by gutosurrex** [comment]
É mais bem feito que no Latex. Por exemplo:

:index:`funções <função>`
:index:`função par <pair: função; par>`
:index:`função constante <pair: função; constante>`

Cria o índice:

Constante
  função, 18

Função, 4
  constante, 18
  par, 7

Par
  função, 7


--

**Comment by hjbortol** [comment]
Ponto para o Sphinx!

**Comment by simas0** [comment]
Este index cria um tag num ponto da página que é acessado no hiperlink do glossário. Eu ainda acho que precisa ser melhorado para funcionar como aquilo que o XML faz na versão do Rob Breezer (Pudget Sound University). Lá você não limita apenas o termo, limita a definição inteira. No Glossário ao se clicar no termo, ele não te direciona para a página, ele apresenta uma caixinha com o trecho demarcado no texto. Isso tem diversas vantagens e traz uma utilidade bastante especial para o glossário.

Em 
``O :index:`vetor soma <vetor soma>` é o vetor que tem origem na origem de `\vec{u}` e extremidade na extremidade de `\vec{v}`.``
apenas delimitamos `vetor soma`, assim não teremos como desenvolver uma ferramenta parecida com a citada porque o computador não vai saber onde termina a definição no texto.

**Comment by gutosurrex** [comment]
No caso em que realmente for uma definição, eu sugiro o uso de `.. glossary::`.

```
.. glossary::

   função
      Uma função é uma relação que satisfaz tudo que a gente quer.
```

Isso também cria um link lá no índice remissivo, mas o Sphinx tem como saber qual é a definição, por exemplo, pra colocar um tooltip quando a gente passa o mouse por cima do nome.

**Comment by simas0** [comment]
Eu usei isso bastante na seção abordagem algébrica de vetores. Mas ainda acho que falta o análogo dentro do texto para definições secundárias como vetor unitário, vetores perpendiculares, etc. Mas que nao faz sentido a definição inteira destacada no texto.

_Enviado do meu Lenovo K33b36 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by simas0** [comment]
Como referenciar no texto um termo que aparece no glossário? Eu gostaria de criar um hiperlink para aquele termo. Eu vi como o @hjbortol  fez para termos matemáticos,

``.. math::   ``
``   a \in A``
``   :label: label_vector_composition``

mas acho que deve ter algo especial para as definições feitas usando  `.. glossary::`.

**Comment by gutosurrex** [comment]
É só usar a diretiva `term` como abaixo:

```
.. glossary::

   função
      Uma coisa muito legal e que todos vão gostar.

Temos que lembrar do que é uma :term:`função`.
```
