### ISSUE TITLE
Como trocar a ordem dos arquivos no roteiro?

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#176]
Não quero que o design do capítulo seja o primeiro a aparecer na metodologia.
![captura de tela de 2017-08-07 21-24-25](https://user-images.githubusercontent.com/16407253/29051142-f0a9d42a-7bb6-11e7-958f-c75360a8e924.png)

**Comment by gutosurrex** [comment]
Esse `*` é um jeito simples que somente inclui todos os arquivos. O ideal é colocar cada nome de arquivo na ordem que você deseja que eles apareçam:

http://www.sphinx-doc.org/en/stable/markup/toctree.html

Depois de incluir todos um por um, vale a pena colocar um `*` para incluir os que sejam incluídos posteriormente por alguém que esqueceu de colocar no TOC.
