### ISSUE TITLE
Muitos cliques para entrar num projeto

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#177]
Sugiro que ao clicar no nome do projeto, sejamos direcionados ao índice do master. A lista de ramos deveria estar disponível em dropdown abaixo do nome do projeto.

Às vezes acho que a BookCloud deveria permitir diferentes perfis de usuários e fazer diferença dos caminhos entre eles.

**Comment by simas0** [comment]
O mesmo deveria acontecer ao se clicar no nome do projeto no canto superior esquerdo da página. Por exemplo, ao clicar em Metodologia, somos direcionados à lista de ramos deste projeto. Acho que deveria haver um menu dropdown com ícone metodologia e abaixo a lista de ramos. Ao se clicar num ramo deveríamos ser direcionados ao índice deste ramo.

Também não me parece fazer muito sentido que ao clicar no nome do ramo no canto superior esquerdo sejamos direcionados a uma página com as opções 'visitar ramo' ou 'novo arquivo'. Acho que deveria ir para o índice do ramo. Precisaremos de outro lugar para se criar novo arquivo.

**Comment by gutosurrex** [comment]
Feito no 0.1
