### ISSUE TITLE
Como editar?

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#181]
Caros,

Agora que estou como coordenador efetivo, estou me familiarizando de fato com a plataforma BookCloud.

Bem, já esbarrei logo na processo de edição na plataforma. Vi um erro de digitação e gostaria de corrigir esse erro. 

Tem uma opção lá em cima "edit" (bem natural, não é?). Ao clicar lá em cima, o sistema pede o nome de um novo ramo. Dou um nome e aí nada acontece.

Tentei procurar no link "syntax" por uma ajuda, mas sem sucesso.

Como proceder?

Obrigado!

**Comment by simas0** [comment]
O problema é que após criar um ramo, o sistema mostra uma mensagem de erro e o usuário fica sem saber o que fazer. @gutosurrex e eu estamos terminando de testar a nova versão da plataforma e nela este problema já está resolvido. Avaliamos que vale mais a pena acelerar a finalização da nova plataforma do que resolver isso. Acreditamos que a nova versão estará no ar dentro de 7 dias cheia de novidades agradáveis. Quando isso acontecer poderemos fechar este issue.

**Comment by gutosurrex** [comment]
Atualmente, o que o usuário deve fazer é:
1 - ignorar o erro
2 - abrir o arquivo no ramo que foi criado
3 - editar normalmente
4 - submeter as alterações com o botão `commit`.

**Comment by simas0** [comment]
O problema inicial foi resolvido, melhor fechar.
