### ISSUE TITLE
Discussões não são criadas com a inclusão de rótulos

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#185]
Acho que tem a ver com as caixas ou figuras antes ou depois da atividade. 

O problema foi identificado nas atividades do final da seção em 
https://www.umlivroaberto.com/BookCloud/Volume_1/ramo_simas/view/GE101-0.html

**Comment by simas0** [comment]
O mesmo não acontece em https://www.umlivroaberto.com/BookCloud/Volume_1/ramo_simas/view/GE101-1

**Comment by simas0** [comment]
Neste arquivo fhá mais exemplos em que isso acontece.

https://www.umlivroaberto.com/BookCloud/Volume_1/ramo_simas/view/GEX01-0

**Comment by gutosurrex** [comment]
Atualmente, o espaço de discussão só aparece quando o rótulo chega ao master. O problema é que temos que ter um lugar único para procurar rótulos (pois é um processo lento). Quando implementarmos o git flow, isso pode ser um problema, mas no momento que isso se tornar um problema eu sugiro que seja aberto um outro issue com mais detalhes da questão.
