### ISSUE TITLE
GitHub: qualquer um pode editar o comentário de qualquer um

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#186]
Caros,

Aqui com o Wanderley, percebemos que qualquer um pode modificar e mensagem de qualquer um. Por exemplo, eu criei uma mensagem e o Wanderley conseguiu modificar o que eu havia escrito.

Não é mais adequado cada um poder modificar só aquilo que escreveu?

**Comment by gutosurrex** [comment]
Não estou conseguindo verificar isso. Aqui com o Fábio, quando ele cria uma mensagem e eu tento modificar logado na minha conta não funciona.

Tente modificar um comentário do fábio e nos informe novamente. Vá até o fim e submeta sua edição.

**Comment by hjbortol** [comment]
Augusto, consegui modificar o seu post:

![image](https://user-images.githubusercontent.com/7694624/29240952-115faefa-7f46-11e7-9a6a-d0fe0ec216a7.png)

**Comment by simas0** [comment]
Eu acho que isso só acontece porque somos todos Membros da organização Livro Aberto. Não acho que seja grave. Procurei nas configurações do GitHub e, ao que me parece, para mudar isso eu precisaria passar todo mundo para Colaborador da organização. Se isso bastar, por favor, feche o issue.

**Comment by hjbortol** [comment]
@simas0,

É muito estranho, mesmo para membros de uma organização, que um membro possa modificar o que foi escrito por outro membro. Haveria um bom motivo para que isto fosse feito?

Bem, se for para fazer certinho, certinho, seria melhor evitar isso: alguém (principalmente sem muito treino) poderia, por engano, fazer a modificação.

Assim, se não der trabalho, eu prefiro que houvesse a mudança: cada um edita o que escreveu. Se der muito trabalho, então pode deixar.

**Comment by gutosurrex** [comment]
Ah... mil desculpas. Eu achei que você estava falando de comentários da plataforma. Aqueles são protegidos.

Aqui no Github outros membros podem editar, mas fica indicado que o comentário foi editado... não sei o que vocês acham, mas podemos ficar assim por enquanto, não?

Só pra colocar minha visão do futuro das nossas discussões. Eu imagino que em um futuro próximo a plataforma vai ter mais funcionalidades de comentários como:
- barra de ferramentas no topo dos comentários (com sintaxe e upload de figuras)
- subscrições para que as pessoas recebam emails
- maneira de citar pessoas...

Dessa forma, vamos poder gradativamente migrar do `GitHub/ensino-medio` para a plataforma. O que vocês acham?

**Comment by hjbortol** [comment]
Ok Augusto! Vou fechar este issue!
