### ISSUE TITLE
Como colocar um link no título de uma seção?

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#187]
Caros, vocês sabem como criar um box (seção) cujo título tenha um link para algum lugar? Tentei assim, mas não fucionou:

`   `FASE DE ELABORAÇÃO: <https://github.com/livro-aberto/ensino_medio/issues/10>`_`
![image](https://user-images.githubusercontent.com/7694624/29211250-5431bdaa-7e6e-11e7-9352-698439d15c0e.png)

**Comment by hjbortol** [comment]
Já vi que o problema é outro: não dá para criar um .. admonition:: antes de uma seção.

**Comment by gutosurrex** [comment]
Eu quero trocar os admonitions por ambientes específicos, como:

```
.. habilidade::
   :aulas: 4
   :bncc: AF101

   Nessa habilidade...
```

```
.. professor::

   Note que devemos considerar que o aluno...
```

Isso permitirá fazer estatísticas, fazer links cruzados, colocar estilos personalizados e outras coisas...

Mas seria bom que a gente já fosse discutindo quais serão os ambientes necessários.
