### ISSUE TITLE
.. admonition:: Tempo previsto

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#189]
@simas0 e @gutosurrex,

Tentei criar um box para o "tempo previsto", mas o sistema simplesmente ignora o código:

`.. admonition:: Tempo previsto`

Aliás, acho que é por isso que as indicações de "tempo previsto" e "fase do projeto" estavam escritos dentro do box "habilidade" ...

**Comment by simas0** [comment]
Você viu a sintaxe? https://www.umlivroaberto.com/BookCloud/sintaxe/master/view/index.html#ambientes-especiais

Eu consegui fazer do modo como está descrito lá. Fiz na seção de vetores e submeti para você. Você precisa revisar as submissões em "requests".

**Comment by hjbortol** [comment]
Funcionou, obrigado! Onde está a opção de "request"?

**Comment by hjbortol** [comment]
Já encontrei, obrigado!

**Comment by hjbortol** [comment]
Ao clicar em "requests", a tela abaixo aparece. como eu vejo exatamente o que foi modificado para comparar?

![image](https://user-images.githubusercontent.com/7694624/29240743-90f2032a-7f41-11e7-9a81-36b5f82caeb7.png)

**Comment by hjbortol** [comment]
Já vi também!
