### ISSUE TITLE
Para o professor deveria ser fechado por default e ao abrir um deveria abrir todos

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#193]
também fechar todos juntos

**Comment by gutosurrex** [comment]
Acho que isso só deveria ser o caso na visualização, correto? No editor o Para o Professor deve sempre estar aberto, não?

**Comment by simas0** [comment]
no editor, nada deve mudar. Na visualização, o ideal é fechado por default. Deve ficar fechado junto com a resposta.

não estou certo da utilidade de de abrir e fechar todos juntos.

**Comment by augustoteixeira** [comment]
Acho que isso ficou obsoleto com o design novo, certo?

Além disso eu aumentei a largura do para o professor.
