### ISSUE TITLE
Problemas na versão 0.1 da BookCloud - já foi lançada!

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#194]
Não consegui encontrar qualquer problema urgente. Mas os problemas abaixo vão gerar algum desconforto nos usuários. Não experimentei fazer um merge ou visualizar um diff. 

1. ctrl+F não busca no editor. [Este problema é especialmente incômodo]
2. título de discussão não pode ter acentos.
3. espaços mal colocados alteram a fonte do texto.
4. espaços entre os dois asteriscos e a palavra, como em ** negrito**, não produz negrito.
5. links externos estão abrindo na mesma aba, deveriam abrir em nova aba.
6. a fonte do texto se altera quando se usa itálico (veja a sintaxe para um exemplo https://www.umlivroaberto.com/BookCloud/sintaxe/master/view/index#basico).

**Comment by simas0** [comment]
A enumeração padrão com #. não faz a), b) como antes. Agora faz 1., 2.

**Comment by gutosurrex** [comment]
Feito!
