### ISSUE TITLE
Imagens BITMAP não estão aparecendo no arquivo PDF

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#197]
https://www.umlivroaberto.com/BookCloud/Volume_1/master/pdf

![image](https://user-images.githubusercontent.com/7694624/29248800-28dfed86-7ff7-11e7-90bd-1ac74a1c603b.png)

**Comment by simas0** [comment]
As imagens inseridas via links não vão para o PDF. Isto será desenvolvido
na próximas semanas junto com o gerenciador de imagens da plataforma. Ja
existe um issue para isso. Vou fechar este.

Em 13 de ago de 2017 07:15, "hjbortol" <notifications@github.com> escreveu:

**Comment by simas0** [comment]
@simas0 teste

_Sent from my Lenovo K33b36 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
