### ISSUE TITLE
Abrir links em uma nova aba

### ISSUE THREAD

**Issue by GladsonAntunes** [livro-aberto/BookCloud#200]
@gutosurrex  e @simas0 , seria melhor se as páginas abrissem sempre em uma nova aba. Algumas vezes queremos comparar algumas coisas ou precisamos recorrer a alguma instrução e isso facilitaria.

Exemplo: Clicando em ambiente de elaboração já abre em uma nova aba, na lista de tópicos do Ensino Médio quando clicamos em um dos Capítulos ou seções deveria abrir em uma nova aba. Quando vamos em Bookclound e clicamos, por exmplo, em issues ou syntax, deveia abrir em uma nova janela.

**Comment by simas0** [comment]
Eu concordo que os links para sintaxe e links externos (issues, por exemplo) deveriam abrir em nova aba e isso já está num outro issue #194 . Mas discordo que toda a navegação aconteça em nova aba porque isso vai incomodar o usuário.

Ainda é possível abrir  duplicar uma aba clicando-se em Ctrl e arrastando a aba (no Firefox) ou clicando na aba com o botão direito e depois em 'duplicar' no Chrome.

@GladsonAntunes, se estiver de acordo, por favor, feche este issue.

**Comment by simas0** [comment]
Outra coisa: eu diria que 'urgente' são coisas que impedem o andamento do trabalho de alguém imediatamente ou impedirá no futuro próximo. 
Dificulte bastante a continuidade ou cause um atraso importante, etc.
Ou gere riscos jurídicos.
Ou cause má impressão...

Não isso. rs :-)

**Comment by gutosurrex** [comment]
Eu coloquei: livro-aberto, issues e sintaxe em nova aba, está bom?

**Comment by GladsonAntunes** [comment]
Está ótimo @gutosurrex . Obrigado!

_Sent from my Samsung SM-G935F using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
