### ISSUE TITLE
Criar ambiente de citação

### ISSUE THREAD

**Issue by GladsonAntunes** [livro-aberto/BookCloud#201]
@gutosurrex , @simas0 , seria interessante que no mode de edição, em ESTILO, tivesse a opção de citação.

Exemplo:
Nessa etapa de escolaridade, merece especial destaque o estudo das funções por seu papel como modelo matemático para analisar e interpretar relações de dependência entre variáveis de duas grandezas em fenômenos do mundo natural ou social, incluindo os trabalhados em componentes de outras áreas de conhecimento[...] (BNCC 2016,p.576)

Da forma que está não há destaque algum no texto.

**Comment by simas0** [comment]
Isso já existe no Sphinx, está na [sintaxe](https://www.umlivroaberto.com/BookCloud/sintaxe/master/view/index#citacao-quotation). Não precisa de ambiente próprio, as poderia haver um botão na barra de ferramentas que dê estes três espaços e inclua `[Autor-ano]_` porque o elaborador pode não saber que é assim que se faz uma citação.

**Comment by GladsonAntunes** [comment]
@simas0 , estou me referindo a citações de texto. Não uma referência a um autor. No abnTex temos o \citacao que reproduz uma indentação própria.

**Comment by simas0** [comment]
Eu também. Veja o link que incluí para a sintaxe na minha última mensagem.

_Enviado do meu Lenovo K33b36 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by simas0** [comment]
Acho que isso foi resolvido. Vou fechar, se discordar, por favor, reabra e esclareça.
