### ISSUE TITLE
Discussão não criada

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#204]
Master vetores, atividade segmento orientado após definição (no meio da página)

_Enviado do meu Lenovo K33b36 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by gutosurrex** [comment]
Não podia ter número no label antes. Agora pode (apesar de eu não aconselhar muito pois a ordem sempre pode mudar, não?)
