### ISSUE TITLE
Too many requests - ao tentar clonar ramos

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#207]
A Cydara está tentando clonar um ramo e a plataforma está impedindo... Conversamos sobre isso outro dia e está acontecendo novamente.

Ela deve estar no terceiro ramo de hoje. Eu criei 2 ou 3. Acho que a limitação de 7 ramos é global e não por usuário.

**Comment by gutosurrex** [comment]
Agora é 50
