### ISSUE TITLE
Mover este repositório, com os ISSUES para "livro-aberto"

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#21]
Precisamos ter tudo num só lugar para facilitar o entendimento do usuário.

**Comment by simas0** [comment]
Isso também deve ser feito para o  simas0/Livro-Aberto-de-Matematica-texto-do-projeto-
Eu clonei ambos os projetos na organização "livro-aberto", mas isso não basta porque perdemos os ISSUES e as atualizações não são automáticas.

**Comment by gutosurrex** [comment]
Feito
