### ISSUE TITLE
Search and Replace

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#214]
No editor, senti falta de um search/replace (por exemplo, procurar por _{i} e substituir por _{I} em um bloco selecionado).

**Comment by gutosurrex** [comment]
Já está implementado usando Ctrl-Shift-F.

Mais funcionalidades:
- Ctrl-F / Cmd-F
Start searching
- Ctrl-G / Cmd-G
Find next
- Shift-Ctrl-G / Shift-Cmd-G
Find previous
- Shift-Ctrl-F / Cmd-Option-F
Replace
- Shift-Ctrl-R / Shift-Cmd-Option-F
Replace all
- Alt-F
Persistent search (dialog doesn't autoclose, enter to find next, Shift-Enter to find previous)
- Alt-G
Jump to line

**Comment by hjbortol** [comment]
Excelente!
