### ISSUE TITLE
Exit sem confirmação

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#215]
Fiz uma edição. Cliquei em EXIT para ignorar as modificações (supostamente). Mas, ao voltar para a edição, as modificações feitas continuam. Não há uma maneira fazer o sistema esquecer todas as minhas modificações?

**Comment by simas0** [comment]
Tem certeza de que isso está acontecendo? Eu pedi para implementar isso é tinha sido feito. Pode ser mais uma coisa que se perdeu na nova versão.

_Enviado do meu Lenovo K33b36 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hjbortol** [comment]
Acho que tem razão. Devo ter clicado em "SAVE" e aí já não dá mais para fazer UNDO (CTRL-Z), não é? Isto poderia ser mudado: o default dos editores é permitir undo, mesmo depois de uma gravação ...

**Comment by gutosurrex** [comment]
Fechando essa, abrindo #216

**Comment by simas0** [comment]
@hjbortol, sim isto é outro issue que abri há algum tempo.

_Enviado do meu Lenovo K33b36 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
