### ISSUE TITLE
Ramo Geometria é do Humberto, mas aparece Marcos Paulo nos commits

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#218]
Veja exemplo. Foi o Humberto quem fez.

![image](https://user-images.githubusercontent.com/16407253/29535797-a89d9f5a-8691-11e7-9808-2a021d3afde7.png)

**Comment by gutosurrex** [comment]
Cara, esse negócio de mudar dono de ramo é uma dor de cabeça... tem que lembrar de mudar isso tb. Acho que agora tá funcionando.
