### ISSUE TITLE
seção Referências bibliográficas não aparece no pdf

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#219]
No html está tudo certo, mas no pdf não está.

Estou gerando o pdf dos roteiros para guardar os aprovados para a equipe de revisão.

**Comment by gutosurrex** [comment]
Eu encontrei as referências na última página do pdf. Isso me parece ser o template canônico do sphinx:

- referências aparecem perto do texto no html (para não obrigar ninguém a ficar pulando de lá pra cá) e podem aparecer 300 vezes pois isso não gasta papel.
- referências aparecem no fim do livro no pdf (pra não ficar repetindo e gastar papel e pra ter um local único onde encontrá-las).

Se eu entendi correto você queria mudar esse padrão, então tem que me explicar melhor como.
