### ISSUE TITLE
Não estou vendo um commit da Dirce

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#220]
@gutosurrex e @simas0,

Hoje abrimos um ramo para a Dirce trabalhar. Ela fez uma pequena modificação e deu um commit. Contudo, a modificação não apareceu para eu revisar. Bem, olhei em vários lugares e não achei. O ideal é que aparecesse logo na tela de login inicial uma mensagem dizendo que há revisões para serem feitas.

Obrigado!

**Comment by simas0** [comment]
É um subramo do ramo Geometria?

Em 24 de ago de 2017 09:42, "hjbortol" <notifications@github.com> escreveu:

**Comment by hjbortol** [comment]
Vi no master que o ramo não foi criado como subramo ... Vou tentar lembrar como fazer isto! Obrigado!

**Comment by hjbortol** [comment]
Talvez @simas0 ou @gutosurrex poderiam acrescentar no projeto Sintaxe um texto explicando como criar um subramo dentro de um ramo ...

**Comment by hjbortol** [comment]
@simas0, eu mesmo não estou conseguindo criar um ramo para mim mesmo como Marcos Paulo fez ...

**Comment by hjbortol** [comment]
Ao criar um ramo, o sistema deveria indicar se o ramo é um ramo ou um subramo de qual ramo ...

**Comment by hjbortol** [comment]
@simas0 e @gutosurrex, vou precisar de ajuda de vocês aqui pois não estou me lembrando como criar um subramo de um ramo ...

**Comment by simas0** [comment]
Evite aproveitar um mesmo issue para diferentes assuntos. 
Respondido em #224

**Comment by gutosurrex** [comment]
Eu vou começar a trabalhar agora em um novo sistema de ramos. Esse sistema atual não está bom para os usuários e além disso o sistema atual está se tornando um gargalo para fazer outras coisas da plataforma, como upload de figuras do jeito correto.
