### ISSUE TITLE
Como criar um novo capítulo?

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#222]
Ao passar o pente fino na seção de vetores, queríamos colocar algumas informações no futuro capítulo sobre transformações geométricas (por exemplo, os pré-requisitos da BNCC). Como criar um novo capítulo?

Para lembrarmos (eu e Dirce):

> (EF08MA15) Reconhecer e construir figuras obtidas por composições de transformações
> geométricas (translação, reflexão e rotação), com o uso de instrumentos de desenho ou de
> softwares de geometria dinâmica.

**Comment by simas0** [comment]
Os capítulos estão todos criados. Você não podia ver porque eu os havia retirado da Tabela de Conteúdos. Para o seu problema específico basta clicar em 
https://www.umlivroaberto.com/BookCloud/Volume_1/Geometria/view/index

Mas se precisar ou quiser alterar a Tabela de Conteúdos, veja discussão a este respeito em #176.

**Comment by hjbortol** [comment]
É curioso o branch se chamar Geometria e ter o conteudo de tudo ...

![image](https://user-images.githubusercontent.com/7694624/29671514-22f3dafa-88c0-11e7-95a6-2ddde30eaa88.png)
