### ISSUE TITLE
Como criar um ramo de projeto ou de um outro ramo na BookCloud?

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#224]
## (A) Para criar um subramo do ramo Geometria (se não é você mesmo o dono do ramo Geometria). 
1. Procure o ramo que deseja clonar (criar subramo) clicando em 'Branches'
![image](https://user-images.githubusercontent.com/16407253/29671755-b51cedea-88c0-11e7-82a8-4a0ee127eed6.png)

2. Entre no ramo Geometria através da lista de ramos (clique em 'VISIT').
![image](https://user-images.githubusercontent.com/16407253/29671862-fbdd5ff8-88c0-11e7-89aa-6f7b7c120f48.png)

3. Agora basta clicar em 'EDIT' que você será levado à dar um nome para o subramo e na sequência será direcionado para a tela em que estava, mas agora no seu próprio ramo.

## (B) Para criar um subramo do seu próprio ramo.

Basta substituir 'view/index' por 'clone' na barra de navegação do navegador de internet.

**Comment by hjbortol** [comment]
Beleza! Estas informações deveriam estar no "Sintaxe" ...
