### ISSUE TITLE
Como reescalar figuras tikz no editor sphinx?

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#226]
No código abaixo, eu gostaria de reescalar toda a imagem. Em latex eu usaria 

> \begin{tikzpicture}[scale=1.2]
> 
> código
> 
> \end{tikzpicture}
> 
A única solução que tenho para isso no código sphinx é usando scope, como abaixo. Existe uma solução melhor?

> .. tikz:: 
>    \begin{scope}[scale=1.2]
>    
>    código
>    
>    \end{scope}

**Comment by gutosurrex** [comment]
Eu não vi nenhuma solução conveniente pra isso. Eu acho essa sua solução bem razoável por hora.

Em breve a gente vai ter que mexer dentro do sphinx e talvez nesse momento apareça uma solução melhor.
