### ISSUE TITLE
Threads: usuários

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#227]
Não para fazer como no GitHub e, ao escrever @ o sistema dá a lista de usários? Caso contrário, tem que retornar, anotar o nome, etc.

![image](https://user-images.githubusercontent.com/7694624/29688891-a3645d36-88f7-11e7-8673-b86250365308.png)

**Comment by simas0** [comment]
Quando o cursor estiver neste campo, tecle a seta para baixo. Acho que
funciona.

Em 24 de ago de 2017 6:11 PM, "hjbortol" <notifications@github.com>
escreveu:

**Comment by gutosurrex** [comment]
Aperte a seta para baixo e ele sugere nomes. Também pode digitar a primeira letra do nome do usuário.

**Comment by hjbortol** [comment]
Esta informação deveria estar escrita no ramo "Sintaxe" e, talvez, até ao lado do próprio campo "Users".

**Comment by gutosurrex** [comment]
Feito
