### ISSUE TITLE
Geogebra e TikZ

### ISSUE THREAD

**Issue by mpfaraujo** [livro-aberto/BookCloud#23]
O Geogebra gera um código TikZ meio sujo q acaba não sendo suportado pela plataforma. Desenhar à mão em TikZ é meio trabalhoso e, provavelmente, os professores irão evitar. Seria importante que a plataforma recebesse direto o código gerado pelo geogebra ou que houvesse outra programa em q os professores pudessem fazer o desenho de forma intuitiva e gerar um código TikZ para colar na plataforma.

**Comment by simas0** [comment]
Pois é, os códigos em tikz gerados pelo geogebra exigem os pacotes e bibliotecas 
`\usepackage{pgf,tikz}, \usepackage{mathrsfs} e \usetikzlibrary{arrows}` que provavelmente não estão entre os da plataforma. Talvez seja só o caso de incluir estes pacotes.

**Comment by mpfaraujo** [comment]
Sim, acredito que seja realmente questão de incluir os pacotes e, se for realmente só esse o problema, ganhamos muita agilidade na inserção de figuras. Acho que tem também os pacotes que permitem definir cores por nomes com o comando \definecolor.

**Comment by simas0** [comment]
Este ISSUE deve ser a maior prioridade no dia de hoje.

**Comment by simas0** [comment]
Movido para o repositório "SphinxEdit".
