### ISSUE TITLE
Como criar uma seção nova dentro de um capítulo?

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#242]
Como fazer para criar uma seção nova dentro de um capítulo?

Meu motivo: eu acho que o roteiro deveria ir para uma seção (que vai ser temporária) e não ficar amarrada no início da primeira seção do capítulo. Isso atrapalha: ter que ficar rolando tudo até chegar onde se tem que escrever de fato.

**Comment by simas0** [comment]
Parece que você quer um arquivo exclusivo para o roteiro na plataforma, certo?

Você pode criar novo arquivo clicando em Volume 1 e depois em Manage.

_Enviado do meu Lenovo K33b36 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by simas0** [comment]
Para criar um novo capítulo, basta user a barra de ferramentas...

_Enviado do meu Lenovo K33b36 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hjbortol** [comment]
Não consegui, o sistema diz que eu não dou o dono deste projeto:

![image](https://user-images.githubusercontent.com/7694624/29889516-cecc1138-8d9a-11e7-980f-8e0e772ce9f7.png)

**Comment by simas0** [comment]
Eu vou criar e copio o roteiro para lá.

_Enviado do meu Lenovo K33b36 usando [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by hjbortol** [comment]
Valeu!

**Comment by simas0** [comment]
Caros, retirei os roteiros já finalizados de funções e geometria para um arquivo separado. Para encontrá-los basta visualizar o índice geral do projeto Volume 1 (este nome me incomoda cada vez mais).

![image](https://user-images.githubusercontent.com/16407253/29947326-5ecf92c0-8e7f-11e7-8dbe-e04321a8a23b.png)

Era este o plano, @hjbortol ?
