### ISSUE TITLE
Como combinar index com bold?

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#254]
Tentei

`**:index:`direção <direção>`**`

e

`** :index:`direção <direção>` **`

mas não funciona ...

**Comment by simas0** [comment]
Isso é necessário? Mesmo que seja não acredito que seja crítico...

**Comment by hjbortol** [comment]
Fábio, eu estou querendo, ao mesmo tempo, gerar uma entrada no index que é um termo que está sendo definido e, portanto, este termo tem que estar em negrito (como eu prefiro) ou itálico (como você prefere). Da maneira como está, a palavra não está saindo nem em negrito e nem em itálico.

O label crítico é porque gostaria de uma resposta rápida à pergunta! :)

![image](https://user-images.githubusercontent.com/7694624/30001929-49ad01e8-9073-11e7-99e8-d9184d0e98b8.png)

**Comment by simas0** [comment]
Entendo... Agora revendo, eu também preciso disso. Mas acho que o motivo é para o rótulo 'urgente' e não 'crítico'. :-)

**Comment by gutosurrex** [comment]
Olás, eu acho que o correto era não colocar o negrito na marra, mas pedir que o sphinx coloque uma ênfase em todas as definições. Dessa forma ninguém precisa ficar lembrando de colocar negrito e fica uniforme e fácil de mudar depois. Vou olhar isso em breve.

**Comment by simas0** [comment]
Incluí o issue #329 e acho que ele contempla isso. Uma solução certa dispensa o URGENTE acima porque não depende de readequação do elaborador.
