### ISSUE TITLE
Possibilitar que se faça comentários sobre o conteúdo de algum arquivo ou ramificação do arquivo.

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#26]

**Comment by gutosurrex** [comment]
Feito!

Vale a pena lembrar:

1. Criamos primeiro um thread (tópico) e dentro dele colocamos comentários
2. Podemos marcar outros usuários e outros arquivos em cada thread
3. Cada comentário pode ser em resposta a um outro
4. Dentro da resposta podemos usar os mesmos comandos de edição da plataforma
5. Comentários devem ter no máximo 2000 caracteres
