### ISSUE TITLE
Refereciando figuras no Sphinx

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#264]
Caros,

Gostaria de no texto ter uma figura e mais adiante fazer uma referência a ela. No LaTeX, as figuras podem ser numeradas e esses números são então usados. No Sphinx, tentei o que se segue mas, no lugar do número, aparece o nome do rótulo. Qual é a saída?

![image](https://user-images.githubusercontent.com/7694624/30250620-e9c057f2-9627-11e7-977a-3a21e798f711.png)

**Comment by gutosurrex** [comment]
Está pronto agora, só olhar em:
https://www.umlivroaberto.com/BookCloud/sintaxe/numfig/view/index#referencias-para-figuras

ou futuramente em:

https://www.umlivroaberto.com/BookCloud/sintaxe/master/view/index#referencias-para-figuras

**Comment by hjbortol** [comment]
Muito muito obrigado!
