### ISSUE TITLE
Como colocar um hyperlink na legenda de uma figura?

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#269]
Tentei combinar os dois comandos, mas não deu certo!

![image](https://user-images.githubusercontent.com/7694624/30380576-596cfa16-9870-11e7-80c4-3b9c33ae3a8f.png)

**Comment by simas0** [comment]
Experimente o código: ` (aspas simples)Link texto <http://example.com/>_(aspas simples)` como em https://www.umlivroaberto.com/BookCloud/sintaxe/master/view/index#referencias-externas

Aqui funcionou direitinho.
