### ISSUE TITLE
Tamanho das figuras no PDF

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#272]
O tamanho deveria ser proporcional ao que está no HTML. Hoje algumas estão do tamanho certo e outras estão em tamanho enorme. Se o problema for que as dimensões são definidas atualmente com px, troque o default da barra de ferramentas pelo correspondente em pt ou outra unidade que sirva para ambos.

**Comment by hjbortol** [comment]
Acho que o problema é mais grave! O parâmetro :width: não está funcionando:

![image](https://user-images.githubusercontent.com/7694624/30452579-96d4f67c-996c-11e7-9eae-ad18076fcd54.png)

**Comment by hjbortol** [comment]
Ignorem minha última mensagem. Era um espaço em branco na indentação.

**Comment by gutosurrex** [comment]
Eu fiz uns experimentos aqui e parece que se a gente colocar o tamanho em unidades `pt` ao invés de `px`, funciona também em `pdf`. Mas essa figura niveis_abstracao_1.png ainda está me deixando com uma pulga atrás da orelha...

**Comment by simas0** [comment]
@gutosurrex, tem certeza de que isso vai resolver o problema das figuras no pdf? Vou pedir para todos fazerem as alterações na plataforma e acertarem o dimensionamento das figuras nesta nova unidade de medida.

**Comment by simas0** [comment]
resolvido
