### ISSUE TITLE
GIF animado

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#273]
Caros, tentei fazer um upload de um GIF animado no servidor de modo que, no PDF, a imagem ficaria estática mas, na plataforma, a animação ocorreria (um plus para a plataforma). O que acontece que o arquivo perde a animação e a resolução fica bem ruim. Este problema **não acontece** quando hospedo a imagem em um servidor externo. Poderiam me ajudar?

Aqui está a animação em questão!

![ggb-interlagos-01](https://user-images.githubusercontent.com/7694624/30438148-e3ad9a24-9946-11e7-8f85-5690fdb7a755.gif)

**Comment by gutosurrex** [comment]
Acho que está funcionando agora, testa lá.

**Comment by hjbortol** [comment]
Hummm ... Fiz um upload e o arquivo é convertido para PNG ...

**Comment by simas0** [comment]
não funciona?

**Comment by hjbortol** [comment]
Não, o arquivo é convertido para um PNG estático ... Funcionou com vocês?

**Comment by gutosurrex** [comment]
Agora acho que foi:

https://www.umlivroaberto.com/BookCloud/sintaxe/figuras/view/index#upload-de-figuras

Humberto, ponto pro sphinx?

**Comment by hjbortol** [comment]
Deu certo! Ponto para o Sphinx!
