### ISSUE TITLE
Como colocar duas imagens em uma figura?

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#274]
Gostaria de colocar duas imagens, uma embaixo da outra, mas de forma que elas contem como uma única "figure", isto é, que o contador de figuras veja as duas imagens como um único bloco.

**Comment by hjbortol** [comment]
Vi na página do Sphinx que há o comando image que parece servir para o que eu quero, mas ele não é reconhecido pela plataforma atual ...

**Comment by gutosurrex** [comment]
O comando `.. image:: _resources/banana.jpg` funciona pra mim... mas não funciona com `urls`. É o mesmo pra você?

**Comment by hjbortol** [comment]
Augusto,

Para mim, image não funciona (mesmo sem url):

![image](https://user-images.githubusercontent.com/7694624/30484715-b089198c-9a01-11e7-980c-cc3fc4d23e32.png)

Mas figure funciona:

![image](https://user-images.githubusercontent.com/7694624/30484729-bc683706-9a01-11e7-9c04-e5a6493ee8a6.png)

**Comment by gutosurrex** [comment]
Image não tem atributos (width e align). Seria simplesmente:

```
.. image:: _resources/bla.png
```

Vendo que você está usando códigos qr, podemos colocar um comando só pra isso no Sphinx... vou olhar se é fácil.

**Comment by gutosurrex** [comment]
Estou fechando. Se não tiver resolvido reabra.
