### ISSUE TITLE
Threads: como acrescentar uma pessoa na discussão depois?

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#275]
Como acrescentar uma pessoa em uma discussão depois que ela foi iniciada?

**Comment by simas0** [comment]
Eu também acho que este é um recurso importante.

**Comment by gutosurrex** [comment]
Basta editar a thread:

![untitled](https://user-images.githubusercontent.com/5384131/30482733-9352e228-99fa-11e7-9136-15c00fdd4074.png)
