### ISSUE TITLE
Problema com minha branch

### ISSUE THREAD

**Issue by Lhaylla** [livro-aberto/BookCloud#278]
Já criei duas branches para eu trabalhar que desapareceram. No "Manage" consigo visualizar a lista de sub-branches ligadas à Geometria (Fabio Simas e do Marcos Paulo) e a minha não está lá.

Alguma sugestão?

**Comment by simas0** [comment]
vou pedir para tornar o seu ramo permanente.

**Comment by gutosurrex** [comment]
Feito
