### ISSUE TITLE
O que significam linhas inteiras em verde claro no diff?

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#296]
Na figura abaixo, não fica claro para mim o que as cores comunicam. Por exemplo: a linha 4 foi editada, ela surge duas vezes, uma em vermelho claro e outra em  verde claro. O diff entende que ela foi inteiramente apagada e reescrita com as alterações? Nesta situação não deveriam estar usadas as cores fortes?

![image](https://user-images.githubusercontent.com/16407253/30774321-1bc91656-a057-11e7-99ba-eacb45ee6833.png)

**Comment by simas0** [comment]
Este outro é muito mais preciso...

![image](https://user-images.githubusercontent.com/16407253/30774433-b15b684e-a058-11e7-8c89-7c13b412368b.png)

**Comment by gutosurrex** [comment]
De fato, o primeiro diff entendeu que uma linha foi inteiramente removida e outra foi inteiramente colocada. Quando se trata disso, ele usa cores claras (as escuras só aparecem para comparar uma mesma linha que foi modificada).

Quanto ao segundo exemplo, ele é mais preciso porque usamos um algoritmo melhor de diff (feito pela Google, hehe). Poderia tentar colocar o algoritmo da Google também no outro diff, mas vai dar um pouco de trabalho.
