### ISSUE TITLE
Controle de versões

### ISSUE THREAD

**Issue by Lhaylla** [livro-aberto/BookCloud#307]
É possível ter acesso a uma versão anterior do meu texto?

**Comment by gutosurrex** [comment]
Olá Lhaylla, ainda não está perfeito, mas pelo menos agora eu adicionei uma funcionalidade que pode ajudar nisso.

Primeiramente, você entra em: https://github.com/livro-aberto/ensino_medio

Depois escolhe o ramo que você quer ver na lista:

![screenshot_2017-09-28_10-25-58](https://user-images.githubusercontent.com/5384131/30968980-725182cc-a437-11e7-9854-7d3aba0e04c4.png)

Depois veja os commits:

![screenshot_2017-09-28_10-25-58](https://user-images.githubusercontent.com/5384131/30970548-d5d15364-a43b-11e7-91dd-0b7644752f01.png)

Em cada commit, quando você clicar, terá as diferenças entre versões.

Se você não quiser ver as diferenças introduzidas por aquele commit, mas todo o texto naquele momento, aperte em Browse files:

![screenshot_2017-09-28_10-25-58](https://user-images.githubusercontent.com/5384131/30970713-37a27d70-a43c-11e7-9738-8448d1d96a4a.png)

Outra coisa, essas mudanças devem ser atualizadas somente de hora em hora.
