### ISSUE TITLE
Visualização das alterações do texto de outros colegas

### ISSUE THREAD

**Issue by Lhaylla** [livro-aberto/BookCloud#308]
No "Manage" é possível visualizar a lista de commits dos colegas. Seria possível visualizar as mudanças que eles fizeram no commit de alguma forma?

Quando mais de uma pessoa está mexendo em um mesmo texto, essa ferramenta torna-se muito útil.

**Comment by gutosurrex** [comment]
Agora isso pode ser feito no Github. De maneira similar a como vemos nosso histórico.
