### ISSUE TITLE
Referenciando figuras no texto - erro

### ISSUE THREAD

**Issue by Lhaylla** [livro-aberto/BookCloud#311]
As figuras não estão sendo referenciadas em nenhuma parte do texto. 

![screen shot 2017-09-27 at 9 05 19 am](https://user-images.githubusercontent.com/10701963/30912467-041393f6-a363-11e7-9500-221b711b51a7.png)

**Comment by simas0** [comment]
Acho que é um problema de sintaxe. Veja este link, por favor: https://www.umlivroaberto.com/BookCloud/sintaxe/master/view/index#referencias-para-figuras-e-tabelas

**Comment by Lhaylla** [comment]
Não mudei nada e elas voltaram a serem referenciadas.
