### ISSUE TITLE
Bug: plataforma não sabe quebrar uma construção inline LaTeX grande

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#333]
![image](https://user-images.githubusercontent.com/7694624/31588372-94342ae8-b1cf-11e7-9d00-c539666f7f9e.png)

**Comment by gutosurrex** [comment]
Isso me parece um problema do MathJax (portanto só vai dar problema no html):
https://stackoverflow.com/a/31693270

 Eu acho que pode ser uma boa ideia não fazer inlines muito grandes pra evitar esse tipo de coisa.

**Comment by simas0** [comment]
Mesmo se a equação estiver destacada em uma linha só para ela, não há quebra automática no html. Uma solução é quebrar a linha manualmente. O comando `math` funciona como matharray.
```

.. math::
   
   \overrightarrow{OG} & = \overrightarrow{OA} + \frac{3}{5}\overrightarrow{AB} = \\
                       & = \frac{3}{5}\left( \overrightarrow{OB} - \overrightarrow{OA}\right) = \\
                       & ...
```
