### ISSUE TITLE
Logotipos não aparecem no PDF da BookCloud

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#338]
Subi os logotipos da Fundação Itaú Social e da Associação Livro Aberto para o servidor, com os mesmos nomes que estão na folha de capa, mas eles não aparecem no PDF (mesmo usando `ctrl+shift+R` para atualizar a página e compilar novamente o arquivo).

Talvez seja necessário trocar as linhas 137 e 210 do arquivo livroaberto.sty, respectivamente, pelas linhas a seguir:

``\tikz[remember picture,overlay] \node[opacity=0.1,inner sep=0pt] at (current page.center){\includegraphics[width=\paperwidth]{{livro-aberto}.jpg}};``

``\includegraphics[width=2cm]{{itau}.jpg} % sponsor logo``

**Comment by gutosurrex** [comment]
Cara, só consegui colocar o do Itau... não entendi ainda a razão.

**Comment by simas0** [comment]
pode ser que a BC transforme hífen em underline? o nome pode estar errado...
