### ISSUE TITLE
Alterar \title{...} e \author{...} no arquivo LaTex gerado pela Plataforma

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#339]
No arquivo tex.tex gerado pela BookCloud trocar

Linha 37: `\title{linux Documentation}` por `\title{Livro Aberto de Matemática}`

Linha 40 `\author{Augusto}` por `\author{ }`, ou simplesmente comentar a linha.

**Comment by gutosurrex** [comment]
Troquei, acho que funcionou...
