### ISSUE TITLE
DokuWiki: não consigo acessar nem redefinir a senha

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#347]
![image](https://user-images.githubusercontent.com/7694624/33081475-9a946cb8-cec1-11e7-9334-2b118e480d70.png)

**Comment by simas0** [comment]
Oi Humberto, reiniciei a sua senha. Vou enviar para o seu whatsapp a nova senha. Se funcionar feche aqui, por favor.

**Comment by hjbortol** [comment]
Fabio, você já enviou a nova senha pelo WhatsApp? Eu ainda não recebi ...

**Comment by hjbortol** [comment]
Resolvido! Obrigado!
