### ISSUE TITLE
Compra de artigo "How students use a software application for visualizing 3D geometric objects to solve problems"

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#348]
Dá para comprar? Aceitam PayPal ... [CC: @Lhaylla]

https://www.learntechlib.org/noaccess/40423/

![image](https://user-images.githubusercontent.com/7694624/33089639-67c5bec4-ced8-11e7-9559-4f75426ff6dd.png)

**Comment by simas0** [comment]
Sim, podemos comprar. Você pode comprar em nome da Associação Livro Aberto e me enviar o recibo, que eu te reembolso.

**Comment by hjbortol** [comment]
Fábio, acho que não dá para comprar com um outro nome. Tenho uma sugestão: cada equipe poderia ter um $$$ e a equipe decidiria como e quando usar o $$$. O que acha?
