### ISSUE TITLE
O IMPA assina o ProQuest?

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#351]
@simas0 e @gutosurrex, vocês sabem se o IMPA assina o ProQuest? Gostaria, por exemplo, de ter acesso a esta tese ...

https://search.proquest.com/openview/91ebc3ac3747a47897efe7e171f19c54/1?pq-origsite=gscholar&cbl=18750&diss=y

**Comment by simas0** [comment]
Não sei. Mas acho que tem a lista dos periódicos assinados no site. Não achei este.
http://biblioteca.impa.br/pergamum/biblioteca/index.php

**Comment by gutosurrex** [comment]
Não consegui baixar não...

**Comment by hjbortol** [comment]
Obrigado pela tentativa. É uma pena que não tenhamos acesso ao ProQuest. O sistema parece oferecer acesso à publicações dos vários tipos que normalmente não daria para acessar de outra maneira.

**Comment by simas0** [comment]
Augusto, pede para a biblioteca assinar, por favor. O IMPA está se envolvendo na pesquisa em educação matemática. Nada mais natural.

**Comment by hjbortol** [comment]
O Sistema ProQuest dá acesso a vários outros assuntos, além de Educação Matemática ... Fiz um test drive gratuito de um mês ...
