### ISSUE TITLE
botões "end" e "home" não funcionam da maneira usual no modo edição

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#36]
O ideal é que eles movam o cursor para o fim ou início da linha que estamos vendo na janela de edição. Mas eles levam para o fim ou início da linha numerada, que pode estar várias linhas visuais acima ou abaixo. Isso causa algum desconforto ao usuário.

**Comment by gutosurrex** [comment]
Vou tentar consertar isso, mas é muito importante que as linhas
(numeradas) sejam curtas. Tanto para o git, quanto para o "review file".

**Comment by simas0** [comment]
Isso de pressionar enter após o ponto final será efetivamente utilizado
pela equipe de elaboração quando eles começarem a utilizar a ferramenta de
revisão.

Fábio
(21) 99735-8504

Em 5 de outubro de 2016 09:46, gutosurrex <notifications@github.com>
escreveu:

> Vou tentar consertar isso, mas é muito importante que as linhas
> (numeradas) sejam curtas. Tanto para o git, quanto para o "review file".
>
>
>
>

**Comment by simas0** [comment]
Movido para o repositório "SphinxEdit".
