### ISSUE TITLE
[TestBookCloud] clone não clona

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#366]
Ao clonar o projeto abaixo:
![image](https://user-images.githubusercontent.com/16407253/34038202-b1c010fe-e172-11e7-80cc-3fbf1be4bae9.png)

Obtenho este ramo:
![image](https://user-images.githubusercontent.com/16407253/34038226-c7af2206-e172-11e7-9203-dbb76b29cb99.png)

**Comment by gutosurrex** [comment]
Você clonou o commit mais atual do master. Mas como eu esqueci de fazer o commit ela ficou em uma versão antiga...
