### ISSUE TITLE
[TestBookCloud] Alinhamento do editor com o visualizador inconstante

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#367]
Alguns títulos funcionam muito bem, mas outros insistem em não funcionar mesmo depois de salvar.

https://photos.app.goo.gl/8h5eHVkYMRPMtWt33

**Comment by gutosurrex** [comment]
Eu acho que essas falhas se devem à falta de um label, ou a labels duplicados.

Mas de qualquer forma, tem uma coisa que incomoda, que é o scroll muito automático quando andamos com o cursor.

Eu acho que deveria acontecer só quando clicamos com o mouse.

**Comment by simas0** [comment]
:+1:
