### ISSUE TITLE
Image too large

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#376]
Tentei fazer o upload da imagem em anexo (2.3 Mb) e o sistema respondeu que ela é grande demais. Não seria conveniente, para a qualidade do material impresso, ter imagens em alta resolução?

![image](https://user-images.githubusercontent.com/7694624/35156133-03063424-fd17-11e7-880a-b3cf572daeda.png)

![18_panneaudeslions partiedroite bisonspoursuivispardeslions](https://user-images.githubusercontent.com/7694624/35156137-072d8e30-fd17-11e7-9ec4-591fd6be6a23.jpg)

**Comment by simas0** [comment]
Concordo! Tinha entendido que a plataforma recebia o arquivo e salvava uma versão bem pequena (para o gerenciador de figuras), uma média para o HTML e uma grande para o PDF.  Não é isso o que acontece, @gutosurrex e @diogor?

**Comment by gutosurrex** [comment]
Correto, ela cria uma versão reduzida para o HTML e mantém a original para o pdf. Mas eu achava que o limite era de 16 Mb. Vou conferir e retorno.

**Comment by gutosurrex** [comment]
Consertei. A plataforma aceitava arquivos maiores, mas o servidor rejeitava. Agora o novo limite é 4 Mb. Mas vale a pena prestar atencão no seguinte:

Uma imagem boa em JPG, com 1.5 Mb deve ser mais que suficiente para imprimir ao longo de toda a largura do livro com qualidade máxima de impressão de 300 dpi. Exceto pelas figuras de página inteira, eu acho que realmente é inútil passar de 1.5 Mb. E em qualquer caso deve ser inútil passar de 3 Mb.
