### ISSUE TITLE
PDF voltou a ser como antigamente (estamos regredindo)

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#386]
Esta é uma página de PDF gerado hoje na plataforma. Semana que vem temos 2 oficinas para professores. Não podemos distribuir um material como este para os professores. 

![image](https://user-images.githubusercontent.com/16407253/36392753-8064430c-158b-11e8-8f1f-06a7e5962fbd.png)

**Comment by gutosurrex** [comment]
Feito
