### ISSUE TITLE
PDF do master não está gerando / Search Global

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#395]
Bem, queria ver como a equipe do Marco Paulo e Eduardo Wagner estavam denotando ângulos do tipo AOB. Pensei: como fazer um "search global", sem ter que ficar abrindo arquivo por arquivo. Não há maneira de fazer isto, não é? Bem, aí veio a ideia: tem o arquivo PDF do master. Posso procurar nele. Mas, ao tentar acessar o PDF, obtive a mensagem de erro a seguir. Help needed ...

![image](https://user-images.githubusercontent.com/7694624/36940067-c05f5ed6-1f1a-11e8-985f-0e2ec4fe4716.png)

**Comment by simas0** [comment]
Havia um problema de sintaxe no arquivo de Funções Quadráticas que impedia a compilação do PDF. O problema foi resolvido ontem.
