### ISSUE TITLE
Problemas com as cores da paleta escolhida

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#396]
A cor atento deveria ser um tom de vermelho, mais precisamente: {RGB}{183,13,40} 
Hoje ela está definida com o RGB do 'aviso' e aviso não está definido. Favor corrigir.

```
\definecolor{atento}{RGB}{183,13,40} %avermelhado
\definecolor{aviso}{RGB}{0,94,176} %azul forte
```
![image](https://user-images.githubusercontent.com/16407253/36998746-c12a2fd4-209c-11e8-9b0e-b4f364be6b10.png)

**Comment by simas0** [comment]
Resolvido

![image](https://user-images.githubusercontent.com/16407253/37051654-d7f6e6f8-2155-11e8-9232-2f5dd907cb4d.png)

**Comment by gutosurrex** [comment]
Mais uma vez... eu preferiria colocar chamativo ou outra coisa no lugar de atento. Uma maçã pode ser chamativa, mas não fica bem uma maçã ser atenta.

Se você trocar no index, me fale que eu troco no arquivo de configuração tikz.
