### ISSUE TITLE
Numeração das figuras desapareceu

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#404]
As numerações de todas as figuras desapareceram. Consequentemente, as referências às figuras ficaram com os rótulos apenas.

![image](https://user-images.githubusercontent.com/7694624/37414718-8984b44e-2788-11e8-8001-e513a18e3a0f.png)

**Comment by simas0** [comment]
Isso não tem muito a ver com o Sphinx, certo?

Foi resolvido.
