### ISSUE TITLE
Merging com erro sempre

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#406]
Recebo a imagem abaixo sempre que tento espalhar as alterações de um ramo, há alguns dias. Eu não me preocupei em criar um issue antes porque o diz que uma mensagem é enviada ao administrador.

![image](https://user-images.githubusercontent.com/16407253/37554447-a0d87a96-29b7-11e8-8d9a-365c5281ddc5.png)

Pergunta: estamos perdendo informação com isso? O que está acontecendo, na prática? Sem estas informações eu não posso definir uma prioridade para este issue.

**Comment by simas0** [comment]
Mensagens como esta surgem ao se fazer commit e ao se clonar também.

**Comment by gutosurrex** [comment]
Alguma notícia?
