### ISSUE TITLE
Figuras em tikz desapareceram da plataforma

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#408]
Não sei se foram todas, mas eu verifiquei o problema em dois lugares no capítulo de vetores: GE101-0 e GE101-1

![image](https://user-images.githubusercontent.com/16407253/37554796-83e54d7e-29bc-11e8-9ff8-2b1d977ded4e.png)

**Comment by gutosurrex** [comment]
Eu fiz uma mudança que deve ter resolvido isso. Você pode recompilar e fechar o issue se tiver consertado?

**Comment by simas0** [comment]
Resolvido
