### ISSUE TITLE
Diff não reflete o resultado final

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#412]
Eu estava alterando as figuras dos capítulos de funções e vetores. Enquanto isso o @hjbortol  alterou o capítulo de projeções e deu commit. Isso desfez algumas das alterações que fiz no capítulo de funções.

![image](https://user-images.githubusercontent.com/16407253/37561422-e431fd38-2a2c-11e8-8e73-e73943f996ab.png)

![image](https://user-images.githubusercontent.com/16407253/37561426-fd381394-2a2c-11e8-99ce-d4109d33d935.png)

![image](https://user-images.githubusercontent.com/16407253/37561432-10ee6492-2a2d-11e8-8f16-1408a188eaf2.png)

etc.

**Comment by simas0** [comment]
Os retrocessos apontados no diff não aconteceram de fato no texto. O problema não está no merge, mas no diff.

**Comment by gutosurrex** [comment]
Estou confuso... você poderia explicar a sua alteração, a do Humberto e o que você esperava que o diff mostrasse?

**Comment by simas0** [comment]
Tenho um novo exemplo:

Eu alterei ontem à noite algumas figuras artísticas no capítulo de funções quadráticas. O Ezequiel submeteu as alterações dele nas figuras matemáticas do capítulo de vetores. No diff mostra as diferenças entre o ramo dele e o master, embora nem todas as diferenças estejam sendo propostas como alterações ao master. No final da página de merge, ele nem oferece aceitar alterações em arquivos de funções, apenas de geometria.
