### ISSUE TITLE
Tabelas do capítulo de Função sumiram

### ISSUE THREAD

**Issue by GladsonAntunes** [livro-aberto/BookCloud#414]
Caros, as tabelas do capítulo de função sumiram. Quando vou em editar elas estão lá digitadas, mas não aparecem após salvarmos. O que pode ter acontecido?

**Comment by simas0** [comment]
Fui eu! Envie o link da página, por favor.

**Comment by GladsonAntunes** [comment]
Aqui Fábio!
https://www.umlivroaberto.org/BookCloud/Volume_1/Algebra_e_Funcoes/view/AF106-1

Uma das figuras da atividade 1.3.1 Colorindo o Mapa também não está aparecendo.

**Comment by GladsonAntunes** [comment]
A tabela da atividade Todo mundo tem Facebook? também não está aparecendo.

https://www.umlivroaberto.org/BookCloud/Volume_1/master/view/AF106-A.html

**Comment by simas0** [comment]
Acho que nem todas, fui eu... Veja o erro de sintaxe que levou ao desaparecimento.

**Errado**
![image](https://user-images.githubusercontent.com/16407253/37591183-6e2281f8-2b49-11e8-8561-76b98683a59d.png)

**Certo**
![image](https://user-images.githubusercontent.com/16407253/37591302-d6014174-2b49-11e8-8b68-97396a23ebf9.png)

Tinha esta outra também

** Errado**
![image](https://user-images.githubusercontent.com/16407253/37591509-8dfa0e78-2b4a-11e8-99f8-d926c3b379de.png)

**Certo**
![image](https://user-images.githubusercontent.com/16407253/37591598-d78e6110-2b4a-11e8-8d32-a4bca38474ab.png)

Todo mundo tem Facebook?

**Errado**
![image](https://user-images.githubusercontent.com/16407253/37591757-48a72aa8-2b4b-11e8-9ac4-c4cb6ffc73b2.png)

**Certo**
![image](https://user-images.githubusercontent.com/16407253/37591822-7f1153b6-2b4b-11e8-93a2-9ddb95ccc58a.png)
