### ISSUE TITLE
Página com comprimento horizontal excessivo (barra de rolagem)

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#420]
Acontece ao menos em https://www.umlivroaberto.org/BookCloud/Volume_1/master/view/GE101-0A.html

![image](https://user-images.githubusercontent.com/16407253/37851572-2f3fb44c-2ebe-11e8-911f-581572985ffc.png)

**Comment by augustoteixeira** [comment]
Não entendi...

**Comment by simas0** [comment]
Misteriosamente consertado!
