### ISSUE TITLE
Box 'Para pesquisar' não está implementado no livro digital

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#429]
![image](https://user-images.githubusercontent.com/16407253/37866144-40f0184c-2f65-11e8-8c18-62492c73198f.png)

**Comment by augustoteixeira** [comment]
![screenshot_2018-03-26_13-07-04](https://user-images.githubusercontent.com/5384131/37918168-c079b05e-310f-11e8-9884-76c630d6c552.png)
