### ISSUE TITLE
LaTeX/PDF: formatação dos itens

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#437]
Acho que os itens estão com um destaque um pouco exagerado: a), b), c) ... em caixas com contorno, em cores diferentes (ver imagem em anexo). Esses itens também são difíceis de se ler em fotocópias em tons de cinza (ver arquivo PDF em anexo) Eu deixaria sem destaque.

![01-destaque-dos-itens](https://user-images.githubusercontent.com/7694624/39827566-adb635ae-538e-11e8-8579-2e83d1941926.jpg)

**Comment by simas0** [comment]
Humberto, o erro foi meu! A designer tinha estipulado outra coisa para a enumeração padrão das seções. O programador de LaTeX que contratamos fez errado e eu não tinha me atentado para isso. Desculpe e obrigado!

Acho que consertei tudo, exceto o Projeto Aplicado, que ainda não tem estilo de seção. Agora os estilos estão assim:

Explorando:
![image](https://user-images.githubusercontent.com/16407253/39872796-72f77fe8-543f-11e8-9187-bdefe5742d63.png)

Organizando
![image](https://user-images.githubusercontent.com/16407253/39872847-9fa6dd68-543f-11e8-94bd-ec8487dbfb7d.png)

Praticando
![image](https://user-images.githubusercontent.com/16407253/39872871-b8ca2192-543f-11e8-83bc-99e13d418d76.png)

Para saber mais
![image](https://user-images.githubusercontent.com/16407253/39872968-1340bbb8-5440-11e8-9762-e6692592b5eb.png)

Exercícios
![image](https://user-images.githubusercontent.com/16407253/39872908-d812649c-543f-11e8-9b5c-b25a46db0a43.png)

Caso isso resolva a sua requisição: feche o issue.
Caso contrário: especifique.

**Comment by hjbortol** [comment]
Beleza!
