### ISSUE TITLE
Ambiente de atividade com erro

### ISSUE THREAD

**Issue by biarc** [livro-aberto/BookCloud#449]
Ola!
As sessões de atividades em alguns momentos ainda aparecem como sessões ordinarias, conforme o print da tela. No primeiro screenshot, a tag de atividade aparece corretamente, no segundo e' onde o erro aparece.
E' possivel prever quando isso ira ocorrer inclusive, dependendo do contexto onde a atividade sera inserida. Por exemplo, quando o capitulo nao e muito colorido ou coisa assim.

(Desculpa pela falta de acentos)
![exemplo1](https://user-images.githubusercontent.com/7039816/40015596-44ff3d58-578a-11e8-8767-9f6bc01da399.png)
![exemplo3](https://user-images.githubusercontent.com/7039816/40015598-45571082-578a-11e8-8d24-4b5fdbf6f4bf.png)

**Comment by augustoteixeira** [comment]
Pode mandar o nome do arquivo?

**Comment by biarc** [comment]
https://www.umlivroaberto.org/BookCloud/Volume_1/master/view/PE104-A.html

**Comment by augustoteixeira** [comment]
Ah, entendi finalmente. O problema é que Atividades deveriam ser ambientes (e não seções) desde o início. Mas os elaboradores fizeram as Atividades como seções e a gente manteve isso mesmo.

Dessa forma, eu coloquei o ambiente Atividade pra funcionar quando ele era uma seção. Mas agora a gente trocou todos eles para ambientes (admonition) para a entrega. Vou tentar resolver isso rápido.

**Comment by augustoteixeira** [comment]
Na verdade era outra coisa. O para saber mais não estava como seção e sim como ambiente. Veja se todos resolveram agora.

**Comment by simas0** [comment]
@biarc, se estiver resolvido, por favor, feche este issue.
