### ISSUE TITLE
O sistema não está mais renderizando fórmulas LaTeX

### ISSUE THREAD

**Issue by hjbortol** [livro-aberto/BookCloud#452]
![image](https://user-images.githubusercontent.com/7694624/52873107-6049fc80-3135-11e9-91e3-7101fc49c029.png)

**Comment by augustoteixeira** [comment]
Olá Humberto, eu dei uma olhada na plataforma e todas as fórmulas que eu vi estavam renderizadas corretamente. Será que você pode alinhar essas duas telas (ou melhor ainda, produzir um exemplo mais simples) para que eu possa entender o que aconteceu?

**Comment by hjbortol** [comment]
Augusto, voltou ao normal. Acho que foi algo temporário! Se voltar o problema, registro aqui! Obrigado!
