### ISSUE TITLE
Trocar o nome "clone" para "editar" e texto da tela seguinte

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#53]
A primeira alteração não é cosmética, o leigo clica em "clone" quando quer "editar".

A segunda (alteração da tela seguinte) deve servir de orientação. Segue o texto:

> Para editar o projeto você precisa ramificá-lo.
> 
> Escolha um nome para o seu ramo. Experimente algo que reflita as alterações que pretende fazer como sugestao_de_atividade, novo_exemplo ou correcoes_tipograficas.
> 
> [CAMPO DE TEXTO]
> O nome do ramo não pode conter espaços, acentos ou caracteres especiais. 
> 
> LEMBRE-SE suas contribuições apenas serão revisadas depois que você sair e clicar em "submeter".

**Comment by simas0** [comment]
O que você acha de tornar os nomes dos ramos automáticos? 

Pode sempre ter nome "edicoes_de_@usuario" e que na lista de ramos tenha ao lado do nome o dia e hora de criação do ramo para fazer diferença entre  dois ramos do mesmo usuário (o que será incomum).

As vantagens são: 
a) tornar a plataforma mais amigável, 
b) padronizar e 
c) evitar nomes feios nos ramos.

**Comment by simas0** [comment]
Quando não se está logado, não surge a opção "clone" nem "edit". Aparece login. Acho isso um erro, deveria ser edit

**Comment by gutosurrex** [comment]
Feito!
