### ISSUE TITLE
Figuras inseridas por links não aparecem no pdf

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#56]

**Comment by hjbortol** [comment]
Caros, acho urgente que as figuras apareçam na versão final do PDF, pois a formatação nesta mídia permite uma leitura mais global (necessária para quem é coordenador), algo que é mais complicada via browser e HTML.

**Comment by simas0** [comment]
Resolvido! As figuras aparecem no PDF quando estão no servidor. Veja #258 para como subir figuras para o servidor da plataforma.
