### ISSUE TITLE
Criar uma caixa para comandos matemática no editor

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#6]
Acredito que vamos precisar de diversos comandos matemáticos que não estão listados no ambiente de edição. Sugiro colocar um botão que abre uma caixa com vários comandos como os que estão no link a seguir. Aliás, acho que o usado no link é opensource. 
https://www.codecogs.com/latex/eqneditor.php

Este outro é mais bonito, mas tem código fechado. 
http://www.hostmath.com/

Deixa eu ser mais claro: nenhum dos que surge nos links acima são exatamente o que eu gostaria. Em nosso ambiente deveria haver apenas um botão que abre uma caixa que contém o que aparece nos links acima.

**Comment by merilx** [comment]
Na outra projeto, estou usando MathType. Ele funciona bem. Pode ser, seria um outra modelo para esta ferramenta. Tem um 30-dia versão de teste e um versão Lite que pode usar para sempre.
[http://www.mathtype.com/en/products/mathtype/default.htm](http://www.mathtype.com/en/products/mathtype/default.htm)

**Comment by simas0** [comment]
Movido para o repositório SphinxEdit".
