### ISSUE TITLE
Visualização do ambiente ver diferenças

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#68]
Aumentar a janela verticalmente, ela ocupa menos de 60% do janela do navegador.

Quebrar linha automaticamente na visualização do diff.

**Comment by simas0** [comment]
Os dois problemas apontados acima não ocorrem no github, por exemplo... Vou aumentar a prioridade para lembrarmos deste issue, ele é importante para o conforto dos Coordenadores de Eixo.

**Comment by gutosurrex** [comment]
Feito!
