### ISSUE TITLE
dúvida plataforma

### ISSUE THREAD

**Issue by Luvelasque** [livro-aberto/BookCloud#71]
Não recebo as modificações que a Letícia fez em seu ramo. 
o que estou fazendo de errado...??

**Comment by simas0** [comment]
Olá @Luvelasque, o seu ramo abaixo possui modificações não submetidas e requerimentos não revisados. Não seriam essas as modificações que você diz não receber?

Probabilidade_Estatistica, (by @Luvelasque) (modified) (has requests) - pdf

**Comment by gutosurrex** [comment]
Quando você está logada e acessa o seu ramo:

https://www.umlivroaberto.com/BookCloud/Volume_1/Probabilidade_Estatistica/view/index.html

você deveria ver acima à direita uma caixinha vermelha escrita `commit`. Nesse caso, você pode clicar lá pra submeter as suas modificações recentes. Depois essa caixinha vermelha deveria mudar pra `requests`. Clicando lá você vai ver as mudanças enviadas pela Letícia.

Fábio, temos que fazer o vídeo tutorial o quanto antes.
