### ISSUE TITLE
telas de edição e html retornam ao início quando salva a edição 

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#75]
Isso acontece com os demais usuários, mas não comigo.

**Comment by gutosurrex** [comment]
Vocês poderiam confirmar se é uma questão de navegadores?

**Comment by simas0** [comment]
Os demais usuários estavam usando o chrome, eu uso o firefox.

Em 1 de nov de 2016 17:24, "gutosurrex" <notifications@github.com> escreveu:

**Comment by gutosurrex** [comment]
Vou trabalhar nos outros navegadores semana que vem.

**Comment by simas0** [comment]
Mesmo no Firefox, a visualização para numa dada posição demora a retornar à posição original e, ao menos quando se está no fim do arquivo, ele não posiciona no local exato que estava antes, mas um pouco acima.

**Comment by simas0** [comment]
Movido para o repositório "SphinxEdit".
