### ISSUE TITLE
O que vocês acham de alguém poder fazer commit para o outro?

### ISSUE THREAD

**Issue by gutosurrex** [livro-aberto/BookCloud#85]
Eu fico às vezes preocupado com alguns ramos que demoram muito pra fazer commit. Isso pode gerar confusão no futuro.

Uma possível solução seria o revisor poder fazer commit para os ramos abaixo do dele. O que vocês acham?

**Comment by simas0** [comment]
Eu concordo com essa possibilidade do revisor fazer commit para um ramo
subordinado a ele. Caso alguém se oponha, podemos implementar o envio de um
e-mail automático para o autor das modificações lembrando que é necessário
submeter as mudanças.

Fábio
(21) 99735-8504

Em 10 de novembro de 2016 16:04, gutosurrex <notifications@github.com>
escreveu:

**Comment by gutosurrex** [comment]
Feito!
