### ISSUE TITLE
ambiente "table"

### ISSUE THREAD

**Issue by cambrainha** [livro-aberto/BookCloud#86]
Não sei se o problema sou eu... mas não estou conseguindo colocar aquele cabeçalho do ambiente table com sucesso... só o tutorial da página não foi suficiente para mim! Help

**Comment by simas0** [comment]
Opa! Não entendi qual é o problema com o cabeçalho. No seu ramo, na seção de funções quadráticas, tem várias tabelas com cabeçalhos (primeira linha) bonitinhas.

**Comment by cambrainha** [comment]
Na verdade era sobre o cabeçalho da sintaxe

.. table::
:widths: 1  3
:column-alignment: left center

Quando coloco isso a tabela não compila.

**Comment by gutosurrex** [comment]
Copia essa que está na sintaxe e tenta ir modificando:

```
.. table:: Optional Caption
    :widths: 3 2 1
    :column-alignment: left center right
    :column-wrapping: true true false

    =========== =========== ===========
    Width 50%   Width 33%   Width 16%
    =========== =========== ===========
    Line 1      This text   This text
                should wrap is always
                onto        in one line.
                multiple
                lines.
    Line 2      Centered.   Right-Aligned.
    Line 3      Centered    Right-Aligned
                Again.      Again.
    =========== =========== ===========
```
Note que todas as linhas depois de `.. table::` começam com quatro espaços.

**Comment by simas0** [comment]
Tem um erro comum que é esquecer a linha antes do ..table

Em 11 de nov de 2016 17:29, "gutosurrex" <notifications@github.com>
escreveu:

**Comment by cambrainha** [comment]
Vou tentar!
Obrigado.

Em 11 de nov de 2016 17:38, "Fabio Simas" <notifications@github.com>
escreveu:

**Comment by cambrainha** [comment]
Consegui gente!!! Obrigado!
Eu estava usando 1 tab, e não 4 espaços!!
