### ISSUE TITLE
Não aceita edição

### ISSUE THREAD

**Issue by mpfaraujo** [livro-aberto/BookCloud#87]
Estou tendo problemas com a edição. Uma parte do texto simplesmente não aparece após clickar em SAVE
![problema](https://cloud.githubusercontent.com/assets/22579036/20498694/473e2688-b015-11e6-975f-50a837a03323.png)

**Comment by gutosurrex** [comment]
Eu entrei na sua versão e essa caixa estava lá. Você só experimentou esse problema dentro da página de edição? Eu não consegui repetir o erro na minha janela de edição. Quando isso acontecer, tente colocar o código no issue (ao invés de um screenshot). Por exemplo:

```
.. admonition:: Para o professor 
      
   Com a realização desta atividade pretende-se introduzir a adição de dois vetores tendo como referência a adição de dois deslocamentos parciais. Define-se, a partir dessa situação, o vetor deslocamento `\overrightarrow{AC}` como sendo a adição dos vetores `\overrightarrow{AB}` e `\overrightarrow{BC}`. O que se quer aqui, de modo inicial, é que os alunos reconheçam o vetor soma pela construção do segmento orientado que une o ponto A, origem do primeiro vetor, ao ponto C, extremo do segundo vetor. A determinação das coordenadas do vetor soma deve ser então obtida com base na representação do próprio vetor na malha quadriculada.
```

**Comment by camilasaj** [comment]
Conseguimos colocar dentro da caixa
