### ISSUE TITLE
~Tikz dentro de caixas 

### ISSUE THREAD

**Issue by mpfaraujo** [livro-aberto/BookCloud#88]
Não consegui inserir uma figura tikz dentro de uma caixa do tipo NOTE, por exemplo.

**Comment by gutosurrex** [comment]
Por favor, me mande um exemplo de código.

Para mim está funcionando assim:
```
.. note::

   Algo
   
   .. tikz:: legenda

      \draw (0,0)--(1,0)--(.5,.6)--(0,0);
```
