### ISSUE TITLE
Colocar botão de referência interna

### ISSUE THREAD

**Issue by camilasaj** [livro-aberto/BookCloud#89]
Para não esquecermos de dar o nome para a seção. 
Assunto discutido na reunião do dia 22/11/2016.

**Comment by camilasaj** [comment]
Quando inserir atividade acrescentar a referência automaticamente.

**Comment by simas0** [comment]
Acredito que além deste botão na barra de ferramentas, os ambientes figura, seção, exercício e atividade quando forem colocados a partir do botão na barra de ferramentas, devem vir com a referência.

**Comment by gutosurrex** [comment]
Feito!
