### ISSUE TITLE
Clicar do lado direito para alinhar com o lado esquerdo.

### ISSUE THREAD

**Issue by GladsonAntunes** [livro-aberto/BookCloud#90]

**Comment by simas0** [comment]
Cabe ressaltar a relação desta tarefa com #83.

**Comment by gutosurrex** [comment]
Ainda não fiz, pois é meio complicado... mas já está funcionando a busca na caixa de edição.

Quando estiver editando, aperte `ctrl-f` e digite o termo procurado. Depois aperte `enter` quantas vezes for necessário até encontrar a ocorrência desejada do termo.

**Comment by simas0** [comment]
Movido para o repositório "SphinxEdit".
