### ISSUE TITLE
Trocar "login" por "edit" no canto superior direito da tela

### ISSUE THREAD

**Issue by simas0** [livro-aberto/BookCloud#93]

**Comment by gutosurrex** [comment]
Mas agora, sempre que tem a possibilidade de editar o texto tem um edit do lado do login, não basta?

**Comment by mpfaraujo** [comment]
Não estou vendo edit em lugar algum agora.

**Comment by mpfaraujo** [comment]
estranhamente agora estou vendo edit ...

**Comment by gutosurrex** [comment]
Erro meu... eu corrigi agorinha.

**Comment by simas0** [comment]
Tem razão. Mas então o botão de "login" e o "edit" nas telas em que aparecem juntos, têm o mesmo efeito, certo? Então o de "login" não é necessário. Mas agora não estou convencido de que esta é a melhor alternativa.

**Comment by gutosurrex** [comment]
Algumas pessoas podem querer dar login sem necessariamente quered editar (por exemplo pra ver o perfil delas).
