### ISSUE TITLE
O processo está demorando muito e será terminado!

### ISSUE THREAD

**Issue by mpfaraujo** [livro-aberto/BookCloud#96]
tenho recebido essa mensagem e não sei o q fazer. Não sei se é instabilidade da minha conexão ou se é algum problema da plataforma.

**Comment by gutosurrex** [comment]
Olá Marcos Paulo,

Você poderia explicar melhor quando isso aconteceu? O que você estava fazendo, com qual frequência essa mensagem tem aparecido? Se possível também cole um screenshot.

**Comment by mpfaraujo** [comment]
A mensagem que apareceu foi exatamente a q eu colei no título do issue. Pelo visto, havia algum erro (q eu não detectei) no tikz q eu estava desenhando. Eu deveria ter explicado melhor o issue ... acontece que a mensagem não me ajudou em nada a resolver o problema q eu estava tendo. Se havia um erro, a plataforma deveria me dizer q havia um erro e me ajudar a corrigir .. a mensagem "O processo está demorando muito e será terminado!" só me deixou perdido. Como eu não desisto, apaguei as ultimas coisas q eu tinha feito e comecei do zero pra ver se continuava o erro ... assim eu resolvi o problema. O meu medo é q outras pessoas que não tenham muita experiência com edições na plataforma possam simplesmente desistir e ficar esperando uma ajuda, o que tornaria a evolução muito lenta.

**Comment by mpfaraujo** [comment]
Sobre a screenshot, da última vez q eu colei um screenshot vc me pediu pra eu dizer o código do erro  e eu não sei onde tirar essa informação. (mas foi por isso q não tirei o screenshot).

**Comment by gutosurrex** [comment]
Olá, eu já entendi o que aconteceu... Isso tem a ver com o issue #49. Na verdade, esse é um problema do latex. Quando dá um erro no tikz, ele faz o processo do latex nunca terminar (e também não fala onde estava o problema), aí estava quebrando a plataforma.

A solução que eu dei foi bastante picareta, eu só coloquei um tempo máximo e depois essa mensagem que você viu. Depois eu vou ver se dá pra colocar um erro mais informativo.

**Comment by simas0** [comment]
Oi @mpfaraujo, o código do erro ao qual o @gutosurrex  se refere é a parte do texto que você estava editando quando o erro aconteceu, por exemplo, o código da figura em sphinxs que você estava fazendo. Se o problema foi corrigido, por favor fechem o issue. Abraço aos dois!

**Comment by mpfaraujo** [comment]
Entendi.
