### ISSUE TITLE
Reply não funcionando nos comentarios

### ISSUE THREAD

**Issue by mpfaraujo** [livro-aberto/BookCloud#97]
Fui dar reply numa tópico do humberto e apareceu como se eu tivesse criando um novo comentário..

**Comment by mpfaraujo** [comment]
Eu fiz como se fosse um novo comentário  e deu certo.  O que parece estranho é que vc tem que dar um titulo (o que não tem muito sentido quando vc está comentando ou respondendo um tópico)

**Comment by gutosurrex** [comment]
Acho que agora está funcionando. E eu tirei os títulos dos comentários que seguem.
